.Dd February 14, 2026
.Dt VOP_READDIR 9
.Os Substrate
.Sh NAME
.Nm VOP_READDIR
.Nd read directory entries
.Sh SYNOPSIS
.In sys/vnode.h
.Ft int
.Fn VOP_READDIR "struct vnode *vp" "struct uio *uio" "struct ucred *cred" "int *eofflag" "int *ncookies" "uint64_t **cookies"
.Sh DESCRIPTION
The
.Fn VOP_READDIR
function reads directory entries from the directory vnode
.Fa vp .
.Pp
The arguments are:
.Bl -tag -width eofflag
.It Fa vp
The vnode of the directory to read.
.It Fa uio
The uio structure describing the read buffer.
.It Fa cred
The credentials of the caller.
.It Fa eofflag
A pointer to an integer that will be set to 1 if the end of the directory is reached, or 0 otherwise.
.It Fa ncookies
A pointer to an integer that will be set to the number of directory cookies returned (if cookies are requested).
.It Fa cookies
A pointer to an array of directory cookies (for NFS support).
.El
.Pp
The directory entries are read into the buffer described by
.Fa uio .
The format of the directory entries is filesystem-specific, but typically follows the
.Vt "struct dirent"
format.
.Sh RETURN VALUES
The
.Fn VOP_READDIR
function returns 0 on success, or an error code on failure.
.Sh ERRORS
.Bl -tag -width Er
.It Bq Er ENOTDIR
The vnode
.Fa vp
is not a directory.
.It Bq Er EIO
An I/O error occurred while reading the directory.
.El
.Sh SEE ALSO
.Xr vnode 9 ,
.Xr VOP_LOOKUP 9
