#!/bin/sh
# contrib/substrate-libtool-shared.sh — teach a libtool-generated `configure`
# (or `libtool` script) that the substrate host builds ELF shared libraries.
#
# libtool's big `case $host_os` dispatch has no substrate branch, so with none
# of its branches matching, the wrapper defaults to "shared libraries not
# supported" and --enable-shared silently produces only static .a archives
# (build_libtool_libs=no).  Substrate is a glibc/ELF-equivalent target — same
# ld.so model, SONAME convention, and shared extension — so fold substrate* in
# alongside linux*/gnu* at every relevant dispatch point.
#
# This is the sed equivalent of the committed
# 0002-libtool-configure-substrate-shared-libs.patch carried by the X libraries
# and libiconv; it is used (instead of a line-numbered patch) by ports whose
# configure is regenerated by autoreconf, where patch offsets would not match.
#
# Usage:  sh substrate-libtool-shared.sh path/to/configure [more configures...]
# Idempotent: re-running on an already-patched file is a no-op.

set -eu

for f in "$@"; do
    [ -f "$f" ] || { echo "substrate-libtool-shared: no such file: $f" >&2; continue; }
    grep -q 'substrate\*)' "$f" && { echo "==> $f already substrate-aware"; continue; }
    sed -i \
        -e 's/\(kopensolaris\*-gnu | gnu\*\))/\1 | substrate*)/g' \
        -e 's/\(kopensolaris\*-gnu | gnu\* | freebsd\*\))/\1 | substrate*)/g' \
        -e 's/\(gnu\* | linux\* | tpf\* | k\*bsd\*-gnu | kopensolaris\*-gnu\))/\1 | substrate*)/g' \
        -e 's/^\([[:space:]]*\)linux\*)/\1linux* | substrate*)/g' \
        "$f"
    echo "==> patched substrate shared-lib support into $f"
done
