.\"
.\" ACCESS(2) - Substrate Native Personality
.\"
.TH ACCESS 2 "January 2026" "Substrate OS" "System Calls"
.SH NAME
access \- check user's permissions for a file
.SH SYNOPSIS
.nf
.B #include <unistd.h>
.PP
.BI "int access(const char *" pathname ", int " mode ");
.fi
.SH DESCRIPTION
.BR access ()
checks whether the calling process can access the file
.IR pathname .
If
.I pathname
is a symbolic link, it is dereferenced.
.PP
The
.I mode
specifies the accessibility check(s) to be performed:
.TP
.B F_OK
Tests for the existence of the file.
.TP
.B R_OK
Tests for read permission.
.TP
.B W_OK
Tests for write permission.
.TP
.B X_OK
Tests for execute permission.
.SH RETURN VALUE
On success, zero is returned.
.PP
On error, \-1 is returned, and
.I errno
is set appropriately.
.SH ERRORS
.TP
.B ENOENT
A component of
.I pathname
does not exist.
.TP
.B EACCES
The requested access would be denied.
.SH NOTES
.SS Substrate Native ABI
.nf
Syscall Number: 33
Arguments:      pathname, mode (on stack)
.fi
.SH SEE ALSO
.BR stat (2),
.BR open (2),
.BR substrate (7)
.SH STANDARDS
POSIX.1-2001, POSIX.1-2008.
