.\" Process this file with
.\" groff -man -Tascii fork.2
.\"
.TH FORK 2 "January 2026" "Substrate Kernel" "System Calls Manual"
.SH NAME
fork \- create a child process
.SH LIBRARY
Standard C library (libc, -lc)
.SH SYNOPSIS
.B #include <unistd.h>
.PP
.BI "pid_t fork(void);"
.SH DESCRIPTION
.B fork()
creates a new process by duplicating the calling process. The new process is referred to as the child process. The calling process is referred to as the parent process.
.PP
The child process and the parent process run in separate memory spaces. At the time of
.B fork()
both memory spaces have the same content. Memory writes, file mappings, and unmappings performed by one of the processes do not affect the other.
.SH RETURN VALUE
On success, the PID of the child process is returned in the parent, and 0 is returned in the child. On failure, -1 is returned in the parent, no child process is created, and errno is set appropriately.
.SH ERRORS
.TP
.B EAGAIN
A system-imposed limit on the number of threads was encountered.
.TP
.B ENOMEM
Failed to allocate the necessary kernel structures or memory for the new process.

.SH SEE ALSO
.BR intro(2)
