.\" Process this file with
.\" groff -man -Tascii getgid.2
.\"
.TH GETGID 2 "January 2026" "Substrate Kernel" "System Calls Manual"
.SH NAME
getgid, getegid \- get group identity
.SH LIBRARY
Standard C library (libc, -lc)
.SH SYNOPSIS
.B #include <unistd.h>
.br
.B #include <sys/types.h>
.PP
.BI "gid_t getgid(void);"
.br
.BI "gid_t getegid(void);"
.SH DESCRIPTION
.B getgid()
returns the real group ID of the calling process.
.PP
.B getegid()
returns the effective group ID of the calling process.
.SH RETURN VALUE
These functions are always successful.

.SH SEE ALSO
.BR intro(2)
