.TH GETPID 2 "February 2026" "Substrate" "System Calls Manual"
.SH NAME
getpid, getppid \- get process identification
.SH SYNOPSIS
.B #include <sys/types.h>
.br
.B #include <unistd.h>
.PP
.B pid_t getpid(void);
.br
.B pid_t getppid(void);
.SH DESCRIPTION
.BR getpid ()
returns the process ID (PID) of the calling process.  (This is often
used by routines that generate unique temporary filenames.)
.PP
.BR getppid ()
returns the process ID of the parent of the calling process.
.SH ERRORS
These functions are always successful.
.SH CONFORMING TO
POSIX.1-2001, POSIX.1-2008, 4.3BSD, SVr4.
.SH SEE ALSO
.BR fork (2),
.BR kill (2),
.BR execve (2)
.SH COLOPHON
This page is part of the Substrate operating system documentation.
