.\" Process this file with
.\" groff -man -Tascii ioctl.2
.\"
.TH IOCTL 2 "January 2026" "Substrate Kernel" "System Calls Manual"
.SH NAME
ioctl \- control device
.SH SYNOPSIS
.B #include <sys/ioctl.h>
.PP
.BI "int ioctl(int " fd ", unsigned long " request ", ...);"
.SH DESCRIPTION
The
.B ioctl
() system call manipulates the underlying device parameters of special
files. In particular, many operating characteristics of character special
files (e.g., terminals) may be controlled with
.B ioctl
() requests.
.SH RETURN VALUE
Usually, on success zero is returned. A few
.B ioctl
() requests use the return value as an output parameter and return a
non-negative value on success. On error, -1 is returned.
.SH ERRORS
.TP
.B EBADF
.I fd
is not a valid open file descriptor.
.TP
.B ENOTTY
The specified request does not apply to the kind of object that the
file descriptor
.I fd
references.
.TP
.B EINVAL
.I request
or
.I argp
is not valid.
