.\"
.\" LSEEK(2) - Substrate Native Personality
.\"
.TH LSEEK 2 "January 2026" "Substrate OS" "System Calls"
.SH NAME
lseek \- reposition read/write file offset
.SH SYNOPSIS
.nf
.B #include <unistd.h>
.PP
.BI "off_t lseek(int " fd ", off_t " offset ", int " whence ");
.fi
.SH DESCRIPTION
.BR lseek ()
repositions the file offset of the open file description associated
with the file descriptor
.I fd
to the argument
.I offset
according to the directive
.IR whence .
.TP
.B SEEK_SET
The file offset is set to
.I offset
bytes.
.TP
.B SEEK_CUR
The file offset is set to its current location plus
.I offset
bytes.
.TP
.B SEEK_END
The file offset is set to the size of the file plus
.I offset
bytes.
.SH RETURN VALUE
On success, the resulting offset location as measured in bytes from
the beginning of the file.
.PP
On error, \-1 is returned, and
.I errno
is set appropriately.
.SH ERRORS
.TP
.B EBADF
.I fd
is not an open file descriptor.
.TP
.B ESPIPE
.I fd
is associated with a pipe, socket, or FIFO.
.TP
.B EINVAL
.I whence
is not valid.
.SH NOTES
.SS Substrate Native ABI
.nf
Syscall Number: 19
Arguments:      fd, offset, whence (on stack)
.fi
.SH SEE ALSO
.BR read (2),
.BR write (2),
.BR open (2),
.BR substrate (7)
.SH STANDARDS
POSIX.1-2001, POSIX.1-2008.
