.\" Process this file with
.\" groff -man -Tascii mkdir.2
.\"
.TH MKDIR 2 "January 2026" "Substrate Kernel" "System Calls Manual"
.SH NAME
mkdir \- create a directory
.SH LIBRARY
Standard C library (libc, -lc)
.SH SYNOPSIS
.B #include <sys/stat.h>
.br
.B #include <sys/types.h>
.PP
.BI "int mkdir(const char *" pathname ", mode_t " mode ");"
.SH DESCRIPTION
.B mkdir()
attempts to create a directory named
.IR pathname .
.SH RETURN VALUE
On success, zero is returned. On error, -1 is returned.
.SH ERRORS
.TP
.B EEXIST
.I pathname
already exists.

.SH SEE ALSO
.BR intro(2)
