.\" Process this file with
.\" groff -man -Tascii mount.2
.\"
.TH MOUNT 2 "January 2026" "TestUnix Kernel" "System Calls Manual"
.SH NAME
mount \- mount filesystem
.SH SYNOPSIS
.B #include <sys/mount.h>
.PP
.BI "int mount(const char *" source ", const char *" target ", const char *" filesystemtype ", unsigned long " mountflags ", const void *" data ");"
.SH DESCRIPTION
.B mount()
attaches the filesystem specified by
.I source
(which is often a device name, but can also be a directory name or a dummy) to the directory specified by
.IR target .
.SH RETURN VALUE
On success, zero is returned. On error, -1 is returned.
.SH ERRORS
.TP
.B EPERM
The caller does not have the required privileges.
.TP
.B ENODEV
Filesystem type not supported.
