.\" Process this file with
.\" groff -man -Tascii rmdir.2
.\"
.TH RMDIR 2 "January 2026" "Substrate Kernel" "System Calls Manual"
.SH NAME
rmdir \- delete a directory
.SH SYNOPSIS
.B #include <unistd.h>
.PP
.BI "int rmdir(const char *" pathname ");"
.SH DESCRIPTION
.B rmdir()
deletes a directory, which must be empty.
.SH RETURN VALUE
On success, zero is returned. On error, -1 is returned.
.SH ERRORS
.TP
.B ENOTEMPTY
The directory is not empty.
.TP
.B ENOENT
The directory does not exist.
