.\" Process this file with
.\" groff -man -Tascii setuid.2
.\"
.TH SETUID 2 "January 2026" "Substrate Kernel" "System Calls Manual"
.SH NAME
setuid \- set user identity
.SH SYNOPSIS
.B #include <sys/types.h>
.br
.B #include <unistd.h>
.PP
.BI "int setuid(uid_t " uid ");"
.SH DESCRIPTION
.B setuid()
sets the effective user ID of the calling process. If the calling process is privileged, the real user ID and saved set-user-ID are also set.
.SH RETURN VALUE
On success, zero is returned. On error, -1 is returned.
.SH ERRORS
.TP
.B EPERM
The user is not privileged and
.I uid
does not match the real UID or saved set-user-ID of the calling process.
