.\" Process this file with
.\" groff -man -Tascii signal.2
.\"
.TH SIGNAL 2 "January 2026" "TestUnix Kernel" "System Calls Manual"
.SH NAME
signal \- ANSI C signal handling
.SH SYNOPSIS
.B #include <signal.h>
.PP
.BI "typedef void (*sighandler_t)(int);"
.br
.BI "sighandler_t signal(int " signum ", sighandler_t " handler ");"
.SH DESCRIPTION
.B signal()
sets the disposition of the signal
.I signum
to
.IR handler ,
which is either
.B SIG_IGN
,
.B SIG_DFL
, or the address of a programmer-defined function (a "signal handler").
.SH RETURN VALUE
.B signal()
returns the previous value of the signal handler, or
.B SIG_ERR
on error.
