.\" Process this file with
.\" groff -man -Tascii thr_new.2
.\"
.TH THR_NEW 2 "January 2026" "TestUnix Kernel" "System Calls Manual"
.SH NAME
thr_new \- create new thread
.SH SYNOPSIS
.B #include <sys/thr.h>
.PP
.BI "int thr_new(struct thr_param *" param ", int " param_size ");"
.SH DESCRIPTION
.B thr_new()
creates a new kernel-scheduled thread of execution within the current process context.
.SH RETURN VALUE
On success, zero is returned. On error, -1 is returned.
