.\" Process this file with
.\" groff -man -Tascii umount.2
.\"
.TH UMOUNT 2 "January 2026" "Substrate Kernel" "System Calls Manual"
.SH NAME
umount \- unmount filesystem
.SH SYNOPSIS
.B #include <sys/mount.h>
.PP
.BI "int umount(const char *" target ");"
.SH DESCRIPTION
.B umount()
removes the attachment of the (topmost) filesystem mounted on
.IR target .
.SH RETURN VALUE
On success, zero is returned. On error, -1 is returned.
.SH ERRORS
.TP
.B EBUSY
The target could not be unmounted because it is busy.
