.\" Process this file with
.\" groff -man -Tascii write.2
.\"
.TH WRITE 2 "January 2026" "TestUnix Kernel" "System Calls Manual"
.SH NAME
write \- write to a file descriptor
.SH SYNOPSIS
.B #include <unistd.h>
.PP
.BI "ssize_t write(int " fd ", const void *" buf ", size_t " count ");"
.SH DESCRIPTION
.B write()
writes up to
.I count
bytes from the buffer starting at
.I buf
to the file referred to by the file descriptor
.IR fd .
.SH RETURN VALUE
On success, the number of bytes written is returned. On error, -1 is returned.
.SH ERRORS
.TP
.B EBADF
.I fd
is not a valid file descriptor or is not open for writing.
.TP
.B EFAULT
.I buf
is outside your accessible address space.
.TP
.B ENOSPC
The device containing the file referred to by
.I fd
has no room for the data.
