.TH IOCTL 2 "February 2026" "Substrate" "System Calls Manual"
.SH NAME
ioctl \- control device
.SH SYNOPSIS
.B #include <sys/ioctl.h>
.PP
.BI "int ioctl(int " fd ", unsigned long " request ", ...);"
.SH DESCRIPTION
The
.BR ioctl ()
system call manipulates the underlying device parameters of special files.
In particular, many operating characteristics of character special files
(e.g., terminals) may be controlled with
.BR ioctl ()
requests.  The argument
.I fd
must be an open file descriptor.
.PP
The second argument is a device-dependent request code.  The third
argument is an untyped pointer to memory.  It's traditionally
.I "char *argp"
(from the days before
.I void *
was valid C), and will be so named for this discussion.
.PP
An
.BR ioctl ()
.I request
has encoded in it whether the argument is an
.I in
parameter or
.I out
parameter, and the size of the argument
.I argp
in bytes.  Macros and defines used in specifying an
.BR ioctl ()
.I request
are located in the file
.IR <sys/ioctl.h> .
.SH RETURN VALUE
Usually, on success zero is returned.  A few
.BR ioctl ()
requests use the return value as an output parameter and return a
nonnegative value on success.  On error, \-1 is returned, and
.I errno
is set appropriately.
.SH ERRORS
.TP
.B EBADF
.I fd
is not a valid file descriptor.
.TP
.B EFAULT
.I argp
references an inaccessible memory area.
.TP
.B EINVAL
.I request
or
.I argp
is not valid.
.TP
.B ENOTTY
.I fd
is not associated with a character special device.
.TP
.B ENOTTY
The specified request does not apply to the kind of object that the file
descriptor
.I fd
references.
.SH CONFORMING TO
No single standard.  Arguments, returns, and semantics of
.BR ioctl ()
vary according to the device driver in question (the call is used as a
catch-all for operations that don't cleanly fit the Unix stream I/O
model).
.SH SEE ALSO
.BR execve (2),
.BR fcntl (2),
.BR open (2),
.BR sd (4),
.BR tty (4)
.SH COLOPHON
This page is part of the Substrate operating system documentation.
