.\"
.\" LINK(2) - Substrate Native Personality
.\"
.TH LINK 2 "January 2026" "Substrate OS" "System Calls"
.SH NAME
link \- make a new name for a file
.SH SYNOPSIS
.nf
.B #include <unistd.h>
.PP
.BI "int link(const char *" oldpath ", const char *" newpath ");
.fi
.SH DESCRIPTION
.BR link ()
creates a new link (also known as a hard link) to an existing file.
.PP
If
.I newpath
exists, it will
.I not
be overwritten.
.PP
This new name may be used exactly as the old one for any operation;
both names refer to the same file and it is impossible to tell
which name was the "original".
.SH RETURN VALUE
On success, zero is returned.
.PP
On error, \-1 is returned, and
.I errno
is set appropriately.
.SH ERRORS
.TP
.B EEXIST
.I newpath
already exists.
.TP
.B ENOENT
A directory component in
.I oldpath
or
.I newpath
does not exist.
.TP
.B EXDEV
.I oldpath
and
.I newpath
are not on the same filesystem.
.SH NOTES
.SS Substrate Native ABI
.nf
Syscall Number: 9 (SYS_LINK)
Arguments:      oldpath, newpath (on stack)
.fi
.SH SEE ALSO
.BR unlink (2),
.BR symlink (2),
.BR rename (2),
.BR substrate (7)
.SH STANDARDS
POSIX.1-2001, POSIX.1-2008.
