#include <sys/signal.h>
#include <sys/proc.h>
#include <exec/perso/linux/linux_user.h>
#include <arch/i386/idt.h>
#include <arch/i386/signal_arch.h>   /* SIG_TRAMPOLINE_ADDR */
#include <string.h>
#include <stddef.h>
#include <stdint.h>

/* These should be exported from sys/arch/i386/signal.c or shared in a header */
extern int copyout(const void *src, void *dst, size_t size);
extern int copyin(const void *src, void *dst, size_t size);
extern int validate_user_addr(const void *addr, size_t size);

/*
 * populate_linux_siginfo - Fill in linux_siginfo_t structure
 *
 * Populates the linux_siginfo_t with signal details.
 */
static void populate_linux_siginfo(linux_siginfo_t *info, int sig, int code) {
    memset(info, 0, sizeof(*info));
    info->si_signo = sig;
    info->si_errno = 0;
    info->si_code = code;

    /* Set source-specific fields */
    /* For now we assume mostly user-generated signals or simple traps */
    if (code == 0) { // SI_USER
        if (current_process) {
            info->_sifields._kill._pid = current_process->pid;
            info->_sifields._kill._uid = current_process->uid;
        }
    } else {
        /* Trap/Fault signals */
        if (current_thread && current_thread->trap_signo == linux_to_native_signal(sig)) {
            info->_sifields._sigfault._addr =
                (void *)(uintptr_t)current_thread->trap_addr;
        } else {
            info->_sifields._sigfault._addr = NULL;
        }
    }
}

void linux_sendsig(void *handler, int sig, uint32_t mask, uint32_t flags, void *regs_ptr) {
    registers_t *regs = (registers_t *)regs_ptr;
    uint32_t esp = regs->useresp;
    int lsig = native_to_linux_signal(sig);
    uint32_t restorer = 0;

    if (current_process && sig > 0 && sig <= NSIG &&
        current_process->linux_sig_restorer[sig - 1]) {
        restorer = (uint32_t)(uintptr_t)current_process->linux_sig_restorer[sig - 1];
    }

    if (flags & SA_SIGINFO) {
        /* rt_sigframe */
        struct linux_rt_sigframe frame;
        memset(&frame, 0, sizeof(frame));

        esp -= sizeof(struct linux_rt_sigframe);
        /* x86 ABI: ESP must be 16-byte aligned before CALL.
         * pretcode at [ESP] acts as return address, so align ESP-4 to 16. */
        esp = ((esp + 4) & ~0xFUL) - 4;

        if (validate_user_addr((void*)(uintptr_t)esp, sizeof(frame)) != 0) {
            sigexit(current_process, SIGSEGV);
            return;
        }

        int code = 0;
        /* Check if this signal was generated by a trap on the current thread */
        if (current_thread && current_thread->trap_signo == sig) {
            code = current_thread->trap_code;
        }

        frame.sig = lsig;
        frame.pinfo = esp + offsetof(struct linux_rt_sigframe, info);
        frame.puc = esp + offsetof(struct linux_rt_sigframe, uc);
        
        /* Populate linux_siginfo_t */
        populate_linux_siginfo(&frame.info, lsig, code);

        frame.uc.uc_flags = 0;
        frame.uc.uc_link = 0;
        if (current_thread) {
            frame.uc.uc_stack.ss_sp = (uint32_t)current_thread->sig_alt_stack.ss_sp;
            frame.uc.uc_stack.ss_size = current_thread->sig_alt_stack.ss_size;
            frame.uc.uc_stack.ss_flags = current_thread->sig_alt_stack.ss_flags;
        }

        frame.uc.uc_sigmask.sig[0] = mask;
        frame.uc.uc_mcontext.eip = regs->eip;
        frame.uc.uc_mcontext.eax = regs->eax;
        frame.uc.uc_mcontext.ebx = regs->ebx;
        frame.uc.uc_mcontext.ecx = regs->ecx;
        frame.uc.uc_mcontext.edx = regs->edx;
        frame.uc.uc_mcontext.edi = regs->edi;
        frame.uc.uc_mcontext.esi = regs->esi;
        frame.uc.uc_mcontext.ebp = regs->ebp;
        frame.uc.uc_mcontext.esp = regs->useresp;
        frame.uc.uc_mcontext.eflags = regs->eflags;
        frame.uc.uc_mcontext.cs = regs->cs;
        frame.uc.uc_mcontext.ss = regs->ss;
        frame.uc.uc_mcontext.ds = regs->ds;
        frame.uc.uc_mcontext.es = regs->es;
        frame.uc.uc_mcontext.fs = regs->fs;
        frame.uc.uc_mcontext.gs = regs->gs;
        frame.uc.uc_mcontext.oldmask = mask;

        /* Linux expects a return trampoline */
        /* For now we use the kernel-mapped trampoline if it matches Linux ABI */
        frame.pretcode = restorer ? restorer : RT_SIG_TRAMPOLINE_ADDR;

        if (copyout(&frame, (void*)(uintptr_t)esp, sizeof(frame)) != 0) {
            sigexit(current_process, SIGSEGV);
            return;
        }

        regs->useresp = esp;
        regs->eip = (uint32_t)handler;
    } else {
        /* traditional sigframe */
        struct linux_sigframe frame;
        memset(&frame, 0, sizeof(frame));

        esp -= sizeof(struct linux_sigframe);
        /* x86 ABI: ESP must be 16-byte aligned before CALL.
         * pretcode at [ESP] acts as return address, so align ESP-4 to 16. */
        esp = ((esp + 4) & ~0xFUL) - 4;

        if (validate_user_addr((void*)(uintptr_t)esp, sizeof(frame)) != 0) {
            sigexit(current_process, SIGSEGV);
            return;
        }

        frame.sig = lsig;
        frame.sc.eip = regs->eip;
        frame.sc.eax = regs->eax;
        frame.sc.ebx = regs->ebx;
        frame.sc.ecx = regs->ecx;
        frame.sc.edx = regs->edx;
        frame.sc.edi = regs->edi;
        frame.sc.esi = regs->esi;
        frame.sc.ebp = regs->ebp;
        frame.sc.esp = regs->useresp;
        frame.sc.eflags = regs->eflags;
        frame.sc.cs = regs->cs;
        frame.sc.ss = regs->ss;
        frame.sc.ds = regs->ds;
        frame.sc.es = regs->es;
        frame.sc.fs = regs->fs;
        frame.sc.gs = regs->gs;
        frame.sc.oldmask = mask;

        frame.pretcode = restorer ? restorer : SIG_TRAMPOLINE_ADDR;

        if (copyout(&frame, (void*)(uintptr_t)esp, sizeof(frame)) != 0) {
            sigexit(current_process, SIGSEGV);
            return;
        }

        regs->useresp = esp;
        regs->eip = (uint32_t)handler;
    }
}

int linux_sys_sigreturn(void *regs_ptr) {
    registers_t *regs = (registers_t *)regs_ptr;
    struct linux_sigframe *frame = (struct linux_sigframe *)(regs->useresp - 8);
    struct linux_sigcontext sc;

    if (copyin(&frame->sc, &sc, sizeof(sc)) != 0) return -1;

    regs->eip = sc.eip;
    regs->eax = sc.eax;
    regs->ebx = sc.ebx;
    regs->ecx = sc.ecx;
    regs->edx = sc.edx;
    regs->edi = sc.edi;
    regs->esi = sc.esi;
    regs->ebp = sc.ebp;
    regs->useresp = sc.esp;
    /* Sanitize EFLAGS: keep kernel-owned bits (IOPL/VM/RF/NT) from the
     * interrupted frame, take only user-modifiable bits from the signal
     * frame.  A raw assignment lets a crafted sigcontext set IOPL=3 and
     * gain ring-3 port I/O (privilege escalation) — matches native
     * sys_sigreturn's EFLAGS_KERNEL_MASK/USER_MASK filter. */
    regs->eflags = (regs->eflags & 0x00033200u) | (sc.eflags & 0xFFCCCDFFu);
    regs->cs = sc.cs | 3;
    regs->ss = sc.ss | 3;
    regs->ds = sc.ds | 3;
    regs->es = sc.es | 3;
    regs->fs = sc.fs | 3;
    regs->gs = sc.gs | 3;

    current_thread->sig_mask = sc.oldmask;
    return regs->eax;
}

int linux_sys_rt_sigreturn(void *regs_ptr) {
    registers_t *regs = (registers_t *)regs_ptr;
    struct linux_rt_sigframe *frame = (struct linux_rt_sigframe *)(regs->useresp - 4);
    struct linux_ucontext uc;

    if (copyin(&frame->uc, &uc, sizeof(uc)) != 0) return -1;

    regs->eip = uc.uc_mcontext.eip;
    regs->eax = uc.uc_mcontext.eax;
    regs->ebx = uc.uc_mcontext.ebx;
    regs->ecx = uc.uc_mcontext.ecx;
    regs->edx = uc.uc_mcontext.edx;
    regs->edi = uc.uc_mcontext.edi;
    regs->esi = uc.uc_mcontext.esi;
    regs->ebp = uc.uc_mcontext.ebp;
    regs->useresp = uc.uc_mcontext.esp;
    /* EFLAGS sanitize — see linux_sys_sigreturn (IOPL escalation guard). */
    regs->eflags = (regs->eflags & 0x00033200u) |
                   (uc.uc_mcontext.eflags & 0xFFCCCDFFu);
    regs->cs = uc.uc_mcontext.cs | 3;
    regs->ss = uc.uc_mcontext.ss | 3;
    regs->ds = uc.uc_mcontext.ds | 3;
    regs->es = uc.uc_mcontext.es | 3;
    regs->fs = uc.uc_mcontext.fs | 3;
    regs->gs = uc.uc_mcontext.gs | 3;

    current_thread->sig_mask = uc.uc_sigmask.sig[0];
    return regs->eax;
}
