#ifndef _LINUX_SYSCALLS_H
#define _LINUX_SYSCALLS_H

#define LINUX_SYS_exit           1
#define LINUX_SYS_fork           2
#define LINUX_SYS_read           3
#define LINUX_SYS_write          4
#define LINUX_SYS_open           5
#define LINUX_SYS_close          6
#define LINUX_SYS_waitpid        7
#define LINUX_SYS_link           9
#define LINUX_SYS_unlink         10
#define LINUX_SYS_execve         11
#define LINUX_SYS_chdir          12
#define LINUX_SYS_time           13
#define LINUX_SYS_mknod          14
#define LINUX_SYS_stat           18
#define LINUX_SYS_lseek          19
#define LINUX_SYS_getpid         20
#define LINUX_SYS_mount          21
#define LINUX_SYS_umount         22
#define LINUX_SYS_setuid         23
#define LINUX_SYS_getuid         24
#define LINUX_SYS_stime          25
#define LINUX_SYS_alarm          27
#define LINUX_SYS_fstat          28
#define LINUX_SYS_access         33
#define LINUX_SYS_sync           36
#define LINUX_SYS_kill           37
#define LINUX_SYS_mkdir          39
#define LINUX_SYS_rmdir          40
#define LINUX_SYS_dup            41
#define LINUX_SYS_pipe           42
#define LINUX_SYS_times          43
#define LINUX_SYS_brk            45
#define LINUX_SYS_setgid         46
#define LINUX_SYS_getgid         47
#define LINUX_SYS_signal         48
#define LINUX_SYS_geteuid        49
#define LINUX_SYS_getegid        50
#define LINUX_SYS_acct           51
#define LINUX_SYS_ioctl          54
#define LINUX_SYS_setpgid        57
#define LINUX_SYS_dup2           63
#define LINUX_SYS_getppid        64
#define LINUX_SYS_getpgrp        65
#define LINUX_SYS_setsid         66
#define LINUX_SYS_lstat          84
#define LINUX_SYS_readlink       85
#define LINUX_SYS_mmap           90
#define LINUX_SYS_munmap         91
#define LINUX_SYS_truncate       92
#define LINUX_SYS_ftruncate      93
#define LINUX_SYS_setitimer      104
#define LINUX_SYS_getitimer      105
#define LINUX_SYS_stat_new       106
#define LINUX_SYS_lstat_new      107
#define LINUX_SYS_fstat_new      108
#define LINUX_SYS_clone          120
#define LINUX_SYS_uname          122
#define LINUX_SYS_getpgid        132
#define LINUX_SYS_fchdir         133
#define LINUX_SYS__llseek        140
#define LINUX_SYS_getdents       141
#define LINUX_SYS_nanosleep      162
#define LINUX_SYS_poll           168
#define LINUX_SYS_rt_sigaction   174
#define LINUX_SYS_rt_sigprocmask 175
#define LINUX_SYS_getcwd         183
#define LINUX_SYS_vfork          190
#define LINUX_SYS_mmap2          192
#define LINUX_SYS_stat64         195
#define LINUX_SYS_lstat64        196
#define LINUX_SYS_fstat64        197
#define LINUX_SYS_getuid32       199
#define LINUX_SYS_getgid32       200
#define LINUX_SYS_geteuid32      201
#define LINUX_SYS_getegid32      202
#define LINUX_SYS_setgid32       214
#define LINUX_SYS_getdents64     220
#define LINUX_SYS_fcntl64        221
#define LINUX_SYS_futex          240
#define LINUX_SYS_set_thread_area 243
#define LINUX_SYS_exit_group     252

#endif /* _LINUX_SYSCALLS_H */
