#include <exec/perso/personality.h>
#include <stddef.h>
#include <arch/i386/syscall.h>
#include <sys/syscall_impl.h>

/* Native-specific syscalls not in syscall_impl.h */
struct thr_param;
extern int sys_thr_new(struct thr_param*, int);
struct pmap_stats;
extern int sys_pmap_stats(struct pmap_stats*);
extern int sys_proc_info(int, void*);
extern int sys_proc_list(int*, size_t);
extern int sys_proc_count(void);
extern int sys_cpu_count(void);
extern int sys_hostname(char*, size_t);
extern int sys_rt_sigreturn(void*);
extern int sys_sigreturn(void*);

static void *native_syscalls[MAX_SYSCALLS] = {
    [SYS_EXIT] = &sys_exit,
    [SYS_FORK] = &sys_fork,
    [SYS_POLL] = &sys_poll,
    [SYS_READ] = &sys_read,
    [SYS_WRITE] = &sys_write,
    [SYS_OPEN] = &sys_open,
    [SYS_CLOSE] = &sys_close,
    [SYS_EXECVE] = &sys_execve,
    [SYS_UNLINK] = (void*)sys_unlink,
    [SYS_TIME] = (void*)sys_time,
    [SYS_SIGRETURN] = (void*)sys_sigreturn,
    [SYS_SIGALTSTACK] = (void*)sys_sigaltstack,
    [SYS_LSEEK] = &sys_lseek,
    [SYS_GETPID] = &sys_getpid,
    [SYS_MOUNT] = &sys_mount,
    [SYS_UMOUNT] = &sys_umount,
    [SYS_SETUID] = &sys_setuid,
    [SYS_GETUID] = &sys_getuid,
    [SYS_ACCESS] = &sys_access,
    [SYS_SYNC] = &sys_sync,
    [SYS_KILL] = &sys_kill,
    [SYS_MKDIR] = &sys_mkdir,
    [SYS_RMDIR] = &sys_rmdir,
    [SYS_PIPE] = &sys_pipe,
    [SYS_SETGID] = &sys_setgid,
    [SYS_IOCTL] = &sys_ioctl,
    [SYS_GETGID] = &sys_getgid,
    [SYS_SIGNAL] = &sys_signal,
    [SYS_GETEUID] = &sys_geteuid,
    [SYS_GETEGID] = &sys_getegid,
    [SYS_ACCT] = &sys_acct,
    [SYS_DUP2] = &sys_dup2,
    [SYS_STAT] = &sys_stat,
    [SYS_LSTAT] = &sys_lstat,
    [SYS_FSTAT] = &sys_fstat,
    [SYS_UNAME] = &sys_uname,
    [SYS_READLINK] = &sys_readlink,
    [SYS_GETDENTS] = &sys_getdents, 
    [SYS_MSYNC] = &sys_msync,
    [SYS_NANOSLEEP] = &sys_nanosleep,
    [SYS_GETCWD] = &sys_getcwd,
    [SYS_PMAP_STATS] = &sys_pmap_stats,
    [SYS_THR_NEW] = &sys_thr_new,
    [SYS_PROC_INFO] = &sys_proc_info,
    [SYS_PROC_LIST] = &sys_proc_list,
    [SYS_PROC_COUNT] = &sys_proc_count,
    [SYS_CPU_COUNT] = &sys_cpu_count,
    [SYS_HOSTNAME] = &sys_hostname,
    [SYS_RT_SIGRETURN] = (void*)sys_rt_sigreturn,
};

static const char *native_names[MAX_SYSCALLS] = {
    [SYS_EXIT] = "exit",
    [SYS_FORK] = "fork",
    [SYS_POLL] = "poll",
    [SYS_READ] = "read",
    [SYS_WRITE] = "write",
    [SYS_OPEN] = "open",
    [SYS_CLOSE] = "close",
    [SYS_EXECVE] = "execve",
    [SYS_UNLINK] = "unlink",
    [SYS_TIME] = "time",
    [SYS_LSEEK] = "lseek",
    [SYS_GETPID] = "getpid",
    [SYS_MOUNT] = "mount",
    [SYS_UMOUNT] = "umount",
    [SYS_SETUID] = "setuid",
    [SYS_GETUID] = "getuid",
    [SYS_ACCESS] = "access",
    [SYS_SYNC] = "sync",
    [SYS_KILL] = "kill",
    [SYS_MKDIR] = "mkdir",
    [SYS_RMDIR] = "rmdir",
    [SYS_PIPE] = "pipe",
    [SYS_SETGID] = "setgid",
    [SYS_IOCTL] = "ioctl",
    [SYS_GETGID] = "getgid",
    [SYS_SIGNAL] = "signal",
    [SYS_GETEUID] = "geteuid",
    [SYS_GETEGID] = "getegid",
    [SYS_ACCT] = "acct",
    [SYS_DUP2] = "dup2",
    [SYS_READLINK] = "readlink",
    [SYS_STAT] = "stat",
    [SYS_LSTAT] = "lstat",
    [SYS_FSTAT] = "fstat",
    [SYS_SIGRETURN] = "sigreturn",
    [SYS_UNAME] = "uname",
    [SYS_GETDENTS] = "getdents",
    [SYS_MSYNC] = "msync",
    [SYS_NANOSLEEP] = "nanosleep",
    [SYS_GETCWD] = "getcwd",
    [SYS_SIGALTSTACK] = "sigaltstack",
    [SYS_PMAP_STATS] = "pmap_stats",
    [SYS_THR_NEW] = "thr_new",
    [SYS_PROC_INFO] = "proc_info",
    [SYS_PROC_LIST] = "proc_list",
    [SYS_PROC_COUNT] = "proc_count",
    [SYS_CPU_COUNT] = "cpu_count",
    [SYS_HOSTNAME] = "hostname",
    [SYS_RT_SIGRETURN] = "rt_sigreturn",
};

static struct syscall_fmt native_fmts[MAX_SYSCALLS] = {
    [SYS_EXIT] = { 1, { ARG_INT } },
    [SYS_FORK] = { 0, { 0 } },
    [SYS_READ] = { 3, { ARG_INT, ARG_PTR, ARG_INT } },
    [SYS_WRITE] = { 3, { ARG_INT, ARG_STR, ARG_INT } },
    [SYS_OPEN] = { 3, { ARG_STR, ARG_HEX, ARG_HEX } },
    [SYS_CLOSE] = { 1, { ARG_INT } },
    [SYS_EXECVE] = { 3, { ARG_STR, ARG_PTR, ARG_PTR } },
    [SYS_UNLINK] = { 1, { ARG_STR } },
    [SYS_TIME] = { 1, { ARG_PTR } },
    [SYS_SIGRETURN] = { 1, { ARG_PTR } },
    [SYS_SIGALTSTACK] = { 2, { ARG_PTR, ARG_PTR } },
    [SYS_LSEEK] = { 4, { ARG_INT, ARG_HEX, ARG_HEX, ARG_INT } },
    [SYS_GETPID] = { 0, { 0 } },
    [SYS_MOUNT] = { 5, { ARG_STR, ARG_STR, ARG_STR, ARG_HEX, ARG_PTR } },
    [SYS_UMOUNT] = { 1, { ARG_STR } },
    [SYS_SETUID] = { 1, { ARG_INT } },
    [SYS_GETUID] = { 0, { 0 } },
    [SYS_ACCESS] = { 2, { ARG_STR, ARG_HEX } },
    [SYS_SYNC] = { 0, { 0 } },
    [SYS_KILL] = { 2, { ARG_INT, ARG_INT } },
    [SYS_MKDIR] = { 2, { ARG_STR, ARG_HEX } },
    [SYS_RMDIR] = { 1, { ARG_STR } },
    [SYS_PIPE] = { 1, { ARG_PTR } },
    [SYS_SETGID] = { 1, { ARG_INT } },
    [SYS_IOCTL] = { 3, { ARG_INT, ARG_HEX, ARG_HEX } },
    [SYS_GETGID] = { 0, { 0 } },
    [SYS_SIGNAL] = { 2, { ARG_INT, ARG_PTR } },
    [SYS_GETEUID] = { 0, { 0 } },
    [SYS_GETEGID] = { 0, { 0 } },
    [SYS_ACCT] = { 1, { ARG_STR } },
    [SYS_DUP2] = { 2, { ARG_INT, ARG_INT } },
    [SYS_READLINK] = { 3, { ARG_STR, ARG_PTR, ARG_INT } },
    [SYS_STAT] = { 2, { ARG_STR, ARG_PTR } },
    [SYS_LSTAT] = { 2, { ARG_STR, ARG_PTR } },
    [SYS_FSTAT] = { 2, { ARG_INT, ARG_PTR } },
    [SYS_UNAME] = { 1, { ARG_PTR } },
    [SYS_GETDENTS] = { 3, { ARG_INT, ARG_PTR, ARG_INT } },
    [SYS_MSYNC] = { 3, { ARG_PTR, ARG_INT, ARG_INT } },
    [SYS_NANOSLEEP] = { 2, { ARG_PTR, ARG_PTR } },
    [SYS_GETCWD] = { 2, { ARG_PTR, ARG_INT } },
    [SYS_POLL] = { 3, { ARG_PTR, ARG_INT, ARG_INT } },
    [SYS_PMAP_STATS] = { 1, { ARG_PTR } },
    [SYS_THR_NEW] = { 2, { ARG_PTR, ARG_INT } },
    [SYS_PROC_INFO] = { 2, { ARG_INT, ARG_PTR } },
    [SYS_PROC_LIST] = { 2, { ARG_PTR, ARG_INT } },
    [SYS_PROC_COUNT] = { 0, { 0 } },
    [SYS_CPU_COUNT] = { 0, { 0 } },
    [SYS_HOSTNAME] = { 2, { ARG_PTR, ARG_INT } },
    [SYS_RT_SIGRETURN] = { 1, { ARG_PTR } },
};

struct personality personality_native = {
    .name = "substrate",
    .syscall_table = native_syscalls,
    .syscall_names = native_names,
    .syscall_fmts = native_fmts,
    .syscall_count = MAX_SYSCALLS
};