#include <exec/perso/personality.h>
#include <stddef.h>
#include <arch/i386/syscall.h>
#include <sys/syscall_impl.h>
#include <sys/resource.h>
#include <sys/times.h>
#include <include/sys/sysinfo.h>
#include <kern/time.h>

extern int sys_mlock(const void *addr, size_t len);
extern int sys_munlock(const void *addr, size_t len);
extern int sys_setsid(void);
extern int sys_getsid(int pid);
extern int sys_setpgid(int pid, int pgid);
extern int sys_getpgid(int pid);
extern int sys_getrusage(int who, struct rusage *usage);
extern int sys_stime(time_t *t);
extern int sys_ioctl(int fd, uint32_t request, void *arg);
extern int sys_ptrace(int req, int pid, int addr, int data);
extern int sys_reboot(int cmd);
extern int sys_sysctl(int *name, unsigned int namelen, void *oldp, size_t *oldlenp, void *newp, size_t newlen);
extern int sys_vm_stats(sys_vmstat_t *stats);
extern int sys_vm_info(sys_vminfo_t *info);
extern int sys_vm_swap(sys_swapinfo_t *swap, size_t *count);
extern int sys_vm_buffers(sys_bufinfo_t *buf);
extern int sys_vm_slabs(sys_slabinfo_t *slabs, size_t *count);
extern int sys_setpriority(int which, int who, int prio);
extern int sys_getpriority(int which, int who);
extern int sys_sethostname(const char *name, size_t len);
struct vm86_struct;  /* forward decl — defined in <sys/vm86.h> */
extern int sys_vm86(struct vm86_struct *info);
extern int sys_set_gsbase(uint32_t base);
extern int sys_proc_pers_name(int perso_id, char *buf, size_t len);

/* Native-specific syscalls are now in syscall_impl.h */

static void *native_sys_mmap(void *addr, size_t length, int prot, int flags,
                             int fd, uint32_t page_offset) {
    return sys_mmap(addr, length, prot, flags, fd, (uint64_t)page_offset << 12);
}

static void *native_syscalls[MAX_SYSCALLS] = {
    [SYS_EXIT] = &sys_exit,
    [SYS_FORK] = &sys_fork,
    [SYS_WAITPID] = &sys_waitpid,
    [SYS_POLL] = &sys_poll,
    [SYS_READ] = &sys_read,
    [SYS_WRITE] = &sys_write,
    [SYS_OPEN] = &sys_open,
    [SYS_OPENAT] = &sys_openat,
    [SYS_CLOSE] = &sys_close,
    [SYS_EXECVE] = &sys_execve,
    [SYS_CHDIR] = &sys_chdir,
    [SYS_CHMOD] = &sys_chmod,
    [SYS_UNLINK] = (void*)sys_unlink,
    [SYS_LINK] = (void*)sys_link,
    [SYS_SYMLINK] = (void*)sys_symlink,
    [SYS_TIME] = (void*)sys_time,
    [SYS_SIGRETURN] = (void*)sys_sigreturn,
    [SYS_SIGALTSTACK] = (void*)sys_sigaltstack,
    [SYS_LSEEK] = &sys_lseek,
    [SYS_STIME] = &sys_stime,
    [SYS_PTRACE] = &sys_ptrace,
    [SYS_ALARM] = &sys_alarm,
    [SYS_GETPID] = &sys_getpid,
    [SYS_MOUNT] = &sys_mount,
    [SYS_UMOUNT] = &sys_umount,
    [SYS_UMOUNT2] = &sys_umount2,
    [SYS_SETUID] = &sys_setuid,
    [SYS_GETUID] = &sys_getuid,
    [SYS_ACCESS] = &sys_access,
    [SYS_SYNC] = &sys_sync,
    [SYS_KILL] = &sys_kill,
    [SYS_MKDIR] = &sys_mkdir,
    [SYS_MKDIRAT] = &sys_mkdirat,
    [SYS_RMDIR] = &sys_rmdir,
    [SYS_PIPE] = &sys_pipe,
    [SYS_SETGID] = &sys_setgid,
    [SYS_IOCTL] = &sys_ioctl,
    [SYS_GETGID] = &sys_getgid,
    [SYS_SIGNAL] = &sys_signal,
    [SYS_GETEUID] = &sys_geteuid,
    [SYS_GETEGID] = &sys_getegid,
    [SYS_ACCT] = &sys_acct,
    [SYS_DUP] = &sys_dup,
    [SYS_DUP2] = &sys_dup2,
    [SYS_DUP3] = &sys_dup3,
    [SYS_PIPE2] = &sys_pipe2,
    [SYS_FCNTL] = &sys_fcntl,
    [SYS_MKNOD] = &sys_mknod,
    [SYS_CHROOT] = &sys_chroot,
    [SYS_CREAT] = (void *)&sys_creat,
    /* SYS_SELECT shares slot 85 with SYS_READLINK in the current
     * header; substrate's libc select() routes through SYS_POLL so
     * the SYS_SELECT entry would just collide.  Don't wire it. */
    [SYS_ACCEPT4] = &sys_accept4,

    /* AF_UNIX sockets (sys/net/af_unix.c) */
    [SYS_SOCKET]      = &sys_socket,
    [SYS_SOCKETPAIR]  = &sys_socketpair,
    [SYS_BIND]        = &sys_bind,
    [SYS_LISTEN]      = &sys_listen,
    [SYS_ACCEPT]      = &sys_accept,
    [SYS_CONNECT]     = &sys_connect,
    [SYS_SEND]        = &sys_send,
    [SYS_RECV]        = &sys_recv,
    [SYS_SENDTO]      = &sys_sendto,
    [SYS_RECVFROM]    = &sys_recvfrom,
    [SYS_SENDMSG]     = &sys_sendmsg,
    [SYS_RECVMSG]     = &sys_recvmsg,
    [SYS_SHUTDOWN]    = &sys_shutdown,
    [SYS_GETSOCKNAME] = &sys_getsockname,
    [SYS_GETPEERNAME] = &sys_getpeername,
    [SYS_GETSOCKOPT]  = &sys_getsockopt,
    [SYS_SETSOCKOPT]  = &sys_setsockopt,
    [SYS_STAT] = &sys_stat,
    [SYS_LSTAT] = &sys_lstat,
    [SYS_FSTAT] = &sys_fstat,
    [SYS_FSTATAT] = &sys_fstatat,
    [SYS_UTIMENSAT] = &sys_utimensat,
    [SYS_FUTIMENS]  = &sys_futimens,
    [SYS_GETXATTR]    = (void *)&sys_getxattr,
    [SYS_LGETXATTR]   = (void *)&sys_lgetxattr,
    [SYS_FGETXATTR]   = (void *)&sys_fgetxattr,
    [SYS_LISTXATTR]   = (void *)&sys_listxattr,
    [SYS_LLISTXATTR]  = (void *)&sys_llistxattr,
    [SYS_FLISTXATTR]  = (void *)&sys_flistxattr,
    [SYS_SETXATTR]    = (void *)&sys_setxattr,
    [SYS_LSETXATTR]   = (void *)&sys_lsetxattr,
    [SYS_FSETXATTR]   = (void *)&sys_fsetxattr,
    [SYS_REMOVEXATTR] = (void *)&sys_removexattr,
    [SYS_LREMOVEXATTR] = (void *)&sys_lremovexattr,
    [SYS_FREMOVEXATTR] = (void *)&sys_fremovexattr,
    [SYS_SEMGET] = (void *)&sys_semget,
    [SYS_SEMOP]  = (void *)&sys_semop,
    [SYS_SEMCTL] = (void *)&sys_semctl,
    [SYS_SHMGET] = (void *)&sys_shmget,
    [SYS_SHMAT]  = (void *)&sys_shmat,
    [SYS_SHMDT]  = (void *)&sys_shmdt,
    [SYS_SHMCTL] = (void *)&sys_shmctl,
    [SYS_UNAME] = &sys_uname,
    [SYS_SETHOSTNAME] = &sys_sethostname,
    [SYS_MODIFY_LDT] = &sys_modify_ldt,
    [SYS_READLINK] = &sys_readlink,
    [SYS_REBOOT] = &sys_reboot,
    [SYS_UMASK] = (void *)&sys_umask,
    [SYS_GETGROUPS] = (void *)&sys_getgroups,
    [SYS_SETGROUPS] = (void *)&sys_setgroups,
    [SYS_WAIT4] = (void *)&sys_wait4,
    [SYS_MMAP] = &native_sys_mmap,
    [SYS_MUNMAP] = &sys_munmap,
    [SYS_TRUNCATE] = &sys_truncate,
    [SYS_FTRUNCATE] = &sys_ftruncate,
    [SYS_FCHMOD] = &sys_fchmod,
    [SYS_FCHOWN] = &sys_fchown,
    [SYS_CHOWN] = &sys_chown,            /* 16  V7 chown, follows symlinks */
    [SYS_LCHOWN] = &sys_lchown,          /* 254  BSD-era no-follow */
    [SYS_LCHMOD] = &sys_lchmod,          /* 274  BSD-era no-follow */
    [SYS_FCHOWNAT] = &sys_fchownat,
    [SYS_LCHOWNAT] = &sys_lchownat,
    [SYS_FCHMODAT] = &sys_fchmodat,
    [SYS_GETDENTS] = &sys_getdents, 
    [SYS_MSYNC] = &sys_msync,
    [SYS_NANOSLEEP] = &sys_nanosleep,
    [SYS_FUTEX] = &sys_futex,
    [SYS_GETCWD] = &sys_getcwd,
    [SYS_PMAP_STATS] = &sys_pmap_stats,
    [SYS_THR_SELF]      = &sys_thr_self,
    [SYS_THR_NEW]       = &sys_thr_new,
    [SYS_THR_EXIT]      = &sys_thr_exit,
    [SYS_THR_JOIN]      = &sys_thr_join,
    [SYS_THR_KILL]      = &sys_thr_kill,
    [SYS_THR_KILL2]     = &sys_thr_kill2,
    [SYS_THR_SUSPEND]   = &sys_thr_suspend,
    [SYS_THR_WAKE]      = &sys_thr_wake,
    [SYS_THR_SET_NAME]  = &sys_thr_set_name,
    [SYS_SCHED_YIELD]   = &sys_yield,
    [SYS_PROC_INFO] = &sys_proc_info,
    [SYS_PROC_LIST] = &sys_proc_list,
    [SYS_PROC_COUNT] = &sys_proc_count,
    [SYS_CPU_COUNT] = &sys_cpu_count,
    [SYS_HOSTNAME] = &sys_hostname,
    [SYS_GETPPID] = &sys_getppid,
    [SYS_SIGACTION] = (void*)sys_sigaction,
    [SYS_SIGPROCMASK] = (void*)sys_sigprocmask,
    [SYS_SIGPENDING] = (void*)sys_sigpending,
    [SYS_SIGSUSPEND] = (void*)sys_sigsuspend,
    [SYS_RT_SIGRETURN] = (void*)sys_rt_sigreturn,
    [SYS_SYSCTL] = &sys_sysctl,
    [SYS_SYSINFO] = &sys_sysinfo,
    [SYS_mlock] = &sys_mlock,
    [SYS_munlock] = &sys_munlock,
    [SYS_SETSID] = &sys_setsid,
    [SYS_GETSID] = &sys_getsid,
    [SYS_SETPGID] = &sys_setpgid,
    [SYS_GETPGID] = &sys_getpgid,
    [SYS_GETRUSAGE] = &sys_getrusage,
    [SYS_RENAME] = &sys_rename,
    [SYS_UNLINKAT] = &sys_unlinkat,
    [SYS_STATFS] = &sys_statfs,
    [SYS_FSTATFS] = &sys_fstatfs,
    [SYS_STATVFS] = &sys_statvfs,
    [SYS_FSTATVFS] = &sys_fstatvfs,
    [SYS_TIMES] = &sys_times,
    [SYS_PROC_THREADS] = &sys_proc_threads,
    [SYS_PROC_THR_COUNT] = &sys_proc_thr_count,
    [SYS_PROC_THR_LIST] = &sys_proc_thr_list,
    [SYS_PROC_FDS] = &sys_proc_fds,
    [SYS_PROC_MAPS] = &sys_proc_maps,
    [SYS_PROC_CWD] = &sys_proc_cwd,
    [SYS_PROC_EXE] = &sys_proc_exe,
    [SYS_PROC_CMDLINE] = &sys_proc_cmdline,
    [SYS_PROC_ENVIRON] = &sys_proc_environ,
    [SYS_VM_STATS] = &sys_vm_stats,
    [SYS_VM_INFO] = &sys_vm_info,
    [SYS_VM_SWAP] = &sys_vm_swap,
    [SYS_VM_BUFFERS] = &sys_vm_buffers,
    [SYS_VM_SLABS] = &sys_vm_slabs,
    [SYS_PROC_PERS_NAME] = &sys_proc_pers_name,
    [SYS_VM86] = (void *)&sys_vm86,
    [SYS_SET_GSBASE] = (void *)&sys_set_gsbase,
    [SYS_SETPRIORITY] = &sys_setpriority,
    [SYS_GETPRIORITY] = &sys_getpriority,
    [SYS_SETITIMER] = &sys_setitimer,
    [SYS_GETITIMER] = &sys_getitimer,
    [SYS_CLOCK_GETTIME] = &sys_clock_gettime,
    [SYS_GETRANDOM] = &sys_getrandom,
};

static const char *native_names[MAX_SYSCALLS] = {
    [SYS_EXIT] = "exit",
    [SYS_FORK] = "fork",
    [SYS_WAITPID] = "waitpid",
    [SYS_POLL] = "poll",
    [SYS_READ] = "read",
    [SYS_WRITE] = "write",
    [SYS_OPEN] = "open",
    [SYS_OPENAT] = "openat",
    [SYS_CLOSE] = "close",
    [SYS_EXECVE] = "execve",
    [SYS_CHDIR] = "chdir",
    [SYS_CHMOD] = "chmod",
    [SYS_UNLINK] = "unlink",
    [SYS_LINK] = "link",
    [SYS_SYMLINK] = "symlink",
    [SYS_TIME] = "time",
    [SYS_LSEEK] = "lseek",
    [SYS_STIME] = "stime",
    [SYS_PTRACE] = "ptrace",
    [SYS_ALARM] = "alarm",
    [SYS_GETPID] = "getpid",
    [SYS_MOUNT] = "mount",
    [SYS_UMOUNT] = "umount",
    [SYS_SETUID] = "setuid",
    [SYS_GETUID] = "getuid",
    [SYS_ACCESS] = "access",
    [SYS_SYNC] = "sync",
    [SYS_KILL] = "kill",
    [SYS_MKDIR] = "mkdir",
    [SYS_MKDIRAT] = "mkdirat",
    [SYS_RMDIR] = "rmdir",
    [SYS_PIPE] = "pipe",
    [SYS_SETGID] = "setgid",
    [SYS_IOCTL] = "ioctl",
    [SYS_GETGID] = "getgid",
    [SYS_SIGNAL] = "signal",
    [SYS_GETEUID] = "geteuid",
    [SYS_GETEGID] = "getegid",
    [SYS_ACCT] = "acct",
    [SYS_DUP] = "dup",
    [SYS_DUP2] = "dup2",
    [SYS_READLINK] = "readlink",
    [SYS_REBOOT] = "reboot",
    [SYS_MMAP] = "mmap",
    [SYS_MUNMAP] = "munmap",
    [SYS_TRUNCATE] = "truncate",
    [SYS_FTRUNCATE] = "ftruncate",
    [SYS_FCHMOD] = "fchmod",
    [SYS_FCHOWN] = "fchown",
    [SYS_LCHOWN] = "lchown",
    [SYS_CHOWN]    = "chown",
    [SYS_LCHMOD]   = "lchmod",
    [SYS_FCHOWNAT] = "fchownat",
    [SYS_LCHOWNAT] = "lchownat",
    [SYS_FCHMODAT] = "fchmodat",
    [SYS_STAT] = "stat",
    [SYS_LSTAT] = "lstat",
    [SYS_FSTAT] = "fstat",
    [SYS_FSTATAT] = "fstatat",
    [SYS_UTIMENSAT] = "utimensat",
    [SYS_FUTIMENS]  = "futimens",
    [SYS_GETXATTR]   = "getxattr",
    [SYS_LGETXATTR]  = "lgetxattr",
    [SYS_FGETXATTR]  = "fgetxattr",
    [SYS_LISTXATTR]  = "listxattr",
    [SYS_LLISTXATTR] = "llistxattr",
    [SYS_FLISTXATTR] = "flistxattr",
    [SYS_SETXATTR]   = "setxattr",
    [SYS_LSETXATTR]  = "lsetxattr",
    [SYS_FSETXATTR]  = "fsetxattr",
    [SYS_REMOVEXATTR]  = "removexattr",
    [SYS_LREMOVEXATTR] = "lremovexattr",
    [SYS_FREMOVEXATTR] = "fremovexattr",
    [SYS_SEMGET] = "semget",
    [SYS_SEMOP]  = "semop",
    [SYS_SEMCTL] = "semctl",
    [SYS_SHMGET] = "shmget",
    [SYS_SHMAT]  = "shmat",
    [SYS_SHMDT]  = "shmdt",
    [SYS_SHMCTL] = "shmctl",
    [SYS_SIGRETURN] = "sigreturn",
    [SYS_UNAME] = "uname",
    [SYS_SETHOSTNAME] = "sethostname",
    [SYS_MODIFY_LDT] = "modify_ldt",
    [SYS_GETDENTS] = "getdents",
    [SYS_MSYNC] = "msync",
    [SYS_NANOSLEEP] = "nanosleep",
    [SYS_FUTEX] = "futex",
    [SYS_GETCWD] = "getcwd",
    [SYS_SIGALTSTACK] = "sigaltstack",
    [SYS_PMAP_STATS] = "pmap_stats",
    [SYS_THR_SELF]     = "thr_self",
    [SYS_THR_NEW]      = "thr_new",
    [SYS_THR_EXIT]     = "thr_exit",
    [SYS_THR_JOIN]     = "thr_join",
    [SYS_THR_KILL]     = "thr_kill",
    [SYS_THR_KILL2]    = "thr_kill2",
    [SYS_THR_SUSPEND]  = "thr_suspend",
    [SYS_THR_WAKE]     = "thr_wake",
    [SYS_THR_SET_NAME] = "thr_set_name",
    [SYS_SCHED_YIELD]  = "sched_yield",
    [SYS_PROC_INFO] = "proc_info",
    [SYS_PROC_LIST] = "proc_list",
    [SYS_PROC_COUNT] = "proc_count",
    [SYS_CPU_COUNT] = "cpu_count",
    [SYS_HOSTNAME] = "hostname",
    [SYS_GETPPID] = "getppid",
    [SYS_SIGACTION] = "sigaction",
    [SYS_SIGPROCMASK] = "sigprocmask",
    [SYS_SIGPENDING] = "sigpending",
    [SYS_SIGSUSPEND] = "sigsuspend",
    [SYS_RT_SIGRETURN] = "rt_sigreturn",
    [SYS_SYSCTL] = "sysctl",
    [SYS_SYSINFO] = "sysinfo",
    [SYS_mlock] = "mlock",
    [SYS_munlock] = "munlock",
    [SYS_SETSID] = "setsid",
    [SYS_GETSID] = "getsid",
    [SYS_SETPGID] = "setpgid",
    [SYS_GETPGID] = "getpgid",
    [SYS_GETRUSAGE] = "getrusage",
    [SYS_RENAME] = "rename",
    [SYS_UNLINKAT] = "unlinkat",
    [SYS_STATFS] = "statfs",
    [SYS_FSTATFS] = "fstatfs",
    [SYS_TIMES] = "times",
    [SYS_PROC_THREADS] = "proc_threads",
    [SYS_PROC_THR_COUNT] = "proc_thr_count",
    [SYS_PROC_THR_LIST] = "proc_thr_list",
    [SYS_PROC_FDS] = "proc_fds",
    [SYS_PROC_MAPS] = "proc_maps",
    [SYS_PROC_CWD] = "proc_cwd",
    [SYS_PROC_EXE] = "proc_exe",
    [SYS_PROC_CMDLINE] = "proc_cmdline",
    [SYS_PROC_ENVIRON] = "proc_environ",
    [SYS_VM_STATS] = "vm_stats",
    [SYS_VM_INFO] = "vm_info",
    [SYS_VM_SWAP] = "vm_swap",
    [SYS_VM_BUFFERS] = "vm_buffers",
    [SYS_VM_SLABS] = "vm_slabs",
    [SYS_PROC_PERS_NAME] = "proc_pers_name",
    [SYS_VM86] = "vm86",
    [SYS_SET_GSBASE] = "set_gsbase",
    [SYS_SETPRIORITY] = "setpriority",
    [SYS_GETPRIORITY] = "getpriority",
    [SYS_SETITIMER] = "setitimer",
    [SYS_GETITIMER] = "getitimer",
    [SYS_CLOCK_GETTIME] = "clock_gettime",
    [SYS_GETRANDOM] = "getrandom",
};

static struct syscall_fmt native_fmts[MAX_SYSCALLS] = {
    [SYS_EXIT] = { 1, { ARG_INT } },
    [SYS_FORK] = { 0, { 0 } },
    [SYS_WAITPID] = { 3, { ARG_INT, ARG_PTR, ARG_INT } },
    [SYS_READ] = { 3, { ARG_INT, ARG_PTR, ARG_INT } },
    [SYS_WRITE] = { 3, { ARG_INT, ARG_STR, ARG_INT } },
    [SYS_OPEN] = { 3, { ARG_STR, ARG_HEX, ARG_HEX } },
    [SYS_OPENAT] = { 4, { ARG_INT, ARG_STR, ARG_HEX, ARG_HEX } },
    [SYS_CLOSE] = { 1, { ARG_INT } },
    [SYS_EXECVE] = { 3, { ARG_STR, ARG_PTR, ARG_PTR } },
    [SYS_CHDIR] = { 1, { ARG_STR } },
    [SYS_CHMOD] = { 2, { ARG_STR, ARG_HEX } },
    [SYS_UNLINK] = { 1, { ARG_STR } },
    [SYS_LINK] = { 2, { ARG_STR, ARG_STR } },
    [SYS_SYMLINK] = { 2, { ARG_STR, ARG_STR } },
    [SYS_TIME] = { 1, { ARG_PTR } },
    [SYS_SIGRETURN] = { 1, { ARG_PTR } },
    [SYS_SIGALTSTACK] = { 2, { ARG_PTR, ARG_PTR } },
    [SYS_LSEEK] = { 4, { ARG_INT, ARG_HEX, ARG_HEX, ARG_INT } },
    [SYS_STIME] = { 1, { ARG_PTR } },
    [SYS_PTRACE] = { 4, { ARG_INT, ARG_INT, ARG_PTR, ARG_INT } },
    [SYS_ALARM] = { 1, { ARG_INT } },
    [SYS_GETPID] = { 0, { 0 } },
    [SYS_MOUNT] = { 5, { ARG_STR, ARG_STR, ARG_STR, ARG_HEX, ARG_PTR } },
    [SYS_UMOUNT] = { 1, { ARG_STR } },
    [SYS_SETUID] = { 1, { ARG_INT } },
    [SYS_GETUID] = { 0, { 0 } },
    [SYS_ACCESS] = { 2, { ARG_STR, ARG_HEX } },
    [SYS_SYNC] = { 0, { 0 } },
    [SYS_KILL] = { 2, { ARG_INT, ARG_INT } },
    [SYS_MKDIR] = { 2, { ARG_STR, ARG_HEX } },
    [SYS_MKDIRAT] = { 3, { ARG_INT, ARG_STR, ARG_HEX } },
    [SYS_RMDIR] = { 1, { ARG_STR } },
    [SYS_PIPE] = { 1, { ARG_PTR } },
    [SYS_SETGID] = { 1, { ARG_INT } },
    [SYS_IOCTL] = { 3, { ARG_INT, ARG_HEX, ARG_HEX } },
    [SYS_GETGID] = { 0, { 0 } },
    [SYS_SIGNAL] = { 2, { ARG_INT, ARG_PTR } },
    [SYS_GETEUID] = { 0, { 0 } },
    [SYS_GETEGID] = { 0, { 0 } },
    [SYS_ACCT] = { 1, { ARG_STR } },
    [SYS_DUP] = { 1, { ARG_INT } },
    [SYS_DUP2] = { 2, { ARG_INT, ARG_INT } },
    [SYS_READLINK] = { 3, { ARG_STR, ARG_PTR, ARG_INT } },
    [SYS_REBOOT] = { 1, { ARG_INT } },
    [SYS_MMAP] = { 6, { ARG_PTR, ARG_INT, ARG_INT, ARG_INT, ARG_INT, ARG_HEX } },
    [SYS_MUNMAP] = { 2, { ARG_PTR, ARG_INT } },
    [SYS_TRUNCATE] = { 3, { ARG_STR, ARG_LONG } },
    [SYS_FTRUNCATE] = { 3, { ARG_INT, ARG_LONG } },
    [SYS_FCHMOD] = { 2, { ARG_INT, ARG_HEX } },
    [SYS_LCHOWN] = { 3, { ARG_STR, ARG_INT, ARG_INT } },
    [SYS_LCHMOD] = { 2, { ARG_STR, ARG_HEX } },
    [SYS_FCHOWN] = { 3, { ARG_INT, ARG_INT, ARG_INT } },
    [SYS_FCHOWNAT] = { 5, { ARG_INT, ARG_STR, ARG_INT, ARG_INT, ARG_HEX } },
    [SYS_LCHOWNAT] = { 5, { ARG_INT, ARG_STR, ARG_INT, ARG_INT, ARG_HEX } },
    [SYS_CHOWN]    = { 3, { ARG_STR, ARG_INT, ARG_INT } },
    [SYS_FCHMODAT] = { 4, { ARG_INT, ARG_STR, ARG_HEX, ARG_HEX } },
    [SYS_STAT] = { 2, { ARG_STR, ARG_PTR } },
    [SYS_LSTAT] = { 2, { ARG_STR, ARG_PTR } },
    [SYS_FSTAT] = { 2, { ARG_INT, ARG_PTR } },
    [SYS_FSTATAT] = { 4, { ARG_INT, ARG_STR, ARG_PTR, ARG_HEX } },
    [SYS_UTIMENSAT] = { 4, { ARG_INT, ARG_STR, ARG_PTR, ARG_HEX } },
    [SYS_FUTIMENS]  = { 2, { ARG_INT, ARG_PTR } },
    [SYS_GETXATTR]   = { 4, { ARG_STR, ARG_STR, ARG_PTR, ARG_INT } },
    [SYS_LGETXATTR]  = { 4, { ARG_STR, ARG_STR, ARG_PTR, ARG_INT } },
    [SYS_FGETXATTR]  = { 4, { ARG_INT, ARG_STR, ARG_PTR, ARG_INT } },
    [SYS_LISTXATTR]  = { 3, { ARG_STR, ARG_PTR, ARG_INT } },
    [SYS_LLISTXATTR] = { 3, { ARG_STR, ARG_PTR, ARG_INT } },
    [SYS_FLISTXATTR] = { 3, { ARG_INT, ARG_PTR, ARG_INT } },
    [SYS_SETXATTR]   = { 5, { ARG_STR, ARG_STR, ARG_PTR, ARG_INT, ARG_INT } },
    [SYS_LSETXATTR]  = { 5, { ARG_STR, ARG_STR, ARG_PTR, ARG_INT, ARG_INT } },
    [SYS_FSETXATTR]  = { 5, { ARG_INT, ARG_STR, ARG_PTR, ARG_INT, ARG_INT } },
    [SYS_REMOVEXATTR]  = { 2, { ARG_STR, ARG_STR } },
    [SYS_LREMOVEXATTR] = { 2, { ARG_STR, ARG_STR } },
    [SYS_FREMOVEXATTR] = { 2, { ARG_INT, ARG_STR } },
    [SYS_SEMGET] = { 3, { ARG_INT, ARG_INT, ARG_INT } },
    [SYS_SEMOP]  = { 3, { ARG_INT, ARG_PTR, ARG_INT } },
    [SYS_SEMCTL] = { 4, { ARG_INT, ARG_INT, ARG_INT, ARG_HEX } },
    [SYS_SHMGET] = { 3, { ARG_INT, ARG_INT, ARG_INT } },
    [SYS_SHMAT]  = { 3, { ARG_INT, ARG_HEX, ARG_INT } },
    [SYS_SHMDT]  = { 1, { ARG_HEX } },
    [SYS_SHMCTL] = { 3, { ARG_INT, ARG_INT, ARG_PTR } },
    [SYS_UNAME] = { 1, { ARG_PTR } },
    [SYS_SETHOSTNAME] = { 2, { ARG_PTR, ARG_INT } },
    [SYS_MODIFY_LDT] = { 3, { ARG_INT, ARG_PTR, ARG_LONG } },
    [SYS_GETDENTS] = { 3, { ARG_INT, ARG_PTR, ARG_INT } },
    [SYS_MSYNC] = { 3, { ARG_PTR, ARG_INT, ARG_INT } },
    [SYS_NANOSLEEP] = { 2, { ARG_PTR, ARG_PTR } },
    [SYS_FUTEX] = { 6, { ARG_PTR, ARG_INT, ARG_INT, ARG_PTR, ARG_PTR, ARG_INT } },
    [SYS_GETCWD] = { 2, { ARG_PTR, ARG_INT } },
    [SYS_POLL] = { 3, { ARG_PTR, ARG_INT, ARG_INT } },
    [SYS_PMAP_STATS] = { 1, { ARG_PTR } },
    [SYS_THR_SELF]     = { 0, { 0 } },
    [SYS_THR_NEW]      = { 2, { ARG_PTR, ARG_INT } },
    [SYS_THR_EXIT]     = { 1, { ARG_PTR } },
    [SYS_THR_JOIN]     = { 2, { ARG_INT, ARG_PTR } },
    [SYS_THR_KILL]     = { 2, { ARG_INT, ARG_INT } },
    [SYS_THR_KILL2]    = { 3, { ARG_INT, ARG_INT, ARG_INT } },
    [SYS_THR_SUSPEND]  = { 1, { ARG_PTR } },
    [SYS_THR_WAKE]     = { 1, { ARG_INT } },
    [SYS_THR_SET_NAME] = { 2, { ARG_INT, ARG_STR } },
    [SYS_SCHED_YIELD]  = { 0, { 0 } },
    [SYS_PROC_INFO] = { 2, { ARG_INT, ARG_PTR } },
    [SYS_PROC_LIST] = { 2, { ARG_PTR, ARG_INT } },
    [SYS_PROC_COUNT] = { 0, { 0 } },
    [SYS_CPU_COUNT] = { 0, { 0 } },
    [SYS_HOSTNAME] = { 2, { ARG_PTR, ARG_INT } },
    [SYS_GETPPID] = { 0, { 0 } },
    [SYS_SIGACTION] = { 3, { ARG_INT, ARG_PTR, ARG_PTR } },
    [SYS_SIGPROCMASK] = { 3, { ARG_INT, ARG_PTR, ARG_PTR } },
    [SYS_SIGPENDING] = { 1, { ARG_PTR } },
    [SYS_SIGSUSPEND] = { 1, { ARG_PTR } },
    [SYS_RT_SIGRETURN] = { 1, { ARG_PTR } },
    [SYS_SYSCTL] = { 6, { ARG_PTR, ARG_INT, ARG_PTR, ARG_PTR, ARG_PTR, ARG_INT } },
    [SYS_SYSINFO] = { 1, { ARG_PTR } },
    [SYS_mlock] = { 2, { ARG_PTR, ARG_INT } },
    [SYS_munlock] = { 2, { ARG_PTR, ARG_INT } },
    [SYS_SETSID] = { 0, { 0 } },
    [SYS_GETSID] = { 1, { ARG_INT } },
    [SYS_SETPGID] = { 2, { ARG_INT, ARG_INT } },
    [SYS_GETPGID] = { 1, { ARG_INT } },
    [SYS_GETRUSAGE] = { 2, { ARG_INT, ARG_PTR } },
    [SYS_RENAME] = { 2, { ARG_STR, ARG_STR } },
    [SYS_UNLINKAT] = { 3, { ARG_INT, ARG_STR, ARG_HEX } },
    [SYS_STATFS] = { 2, { ARG_STR, ARG_PTR } },
    [SYS_FSTATFS] = { 2, { ARG_INT, ARG_PTR } },
    [SYS_TIMES] = { 1, { ARG_PTR } },
    [SYS_PROC_THREADS] = { 3, { ARG_INT, ARG_PTR, ARG_PTR } },
    [SYS_PROC_THR_COUNT] = { 1, { ARG_INT } },
    [SYS_PROC_THR_LIST] = { 3, { ARG_INT, ARG_PTR, ARG_INT } },
    [SYS_PROC_FDS] = { 3, { ARG_INT, ARG_PTR, ARG_PTR } },
    [SYS_PROC_MAPS] = { 3, { ARG_INT, ARG_PTR, ARG_PTR } },
    [SYS_PROC_CWD] = { 3, { ARG_INT, ARG_PTR, ARG_INT } },
    [SYS_PROC_EXE] = { 3, { ARG_INT, ARG_PTR, ARG_INT } },
    [SYS_PROC_CMDLINE] = { 3, { ARG_INT, ARG_PTR, ARG_PTR } },
    [SYS_PROC_ENVIRON] = { 3, { ARG_INT, ARG_PTR, ARG_PTR } },
    [SYS_VM_STATS] = { 1, { ARG_PTR } },
    [SYS_VM_INFO] = { 1, { ARG_PTR } },
    [SYS_VM_SWAP] = { 2, { ARG_PTR, ARG_PTR } },
    [SYS_VM_BUFFERS] = { 1, { ARG_PTR } },
    [SYS_VM_SLABS] = { 2, { ARG_PTR, ARG_PTR } },
    [SYS_PROC_PERS_NAME] = { 3, { ARG_INT, ARG_PTR, ARG_INT } },
    [SYS_VM86] = { 1, { ARG_PTR } },
    [SYS_SET_GSBASE] = { 1, { ARG_HEX } },
    [SYS_SETPRIORITY] = { 3, { ARG_INT, ARG_INT, ARG_INT } },
    [SYS_GETPRIORITY] = { 2, { ARG_INT, ARG_INT } },
    [SYS_SETITIMER] = { 3, { ARG_INT, ARG_PTR, ARG_PTR } },
    [SYS_GETITIMER] = { 2, { ARG_INT, ARG_PTR } },
    [SYS_CLOCK_GETTIME] = { 2, { ARG_INT, ARG_PTR } },
    [SYS_GETRANDOM] = { 3, { ARG_PTR, ARG_INT, ARG_HEX } },
};

extern void sendsig(void *handler, int sig, uint32_t mask, uint32_t flags, void *regs);
extern int sys_sigreturn(void *regs);
extern int sys_rt_sigreturn(void *regs);

struct personality personality_native = {
    .name = "substrate",
    .id = PERS_NATIVE,
    .syscall_table = native_syscalls,
    .syscall_names = native_names,
    .syscall_fmts = native_fmts,
    .syscall_count = MAX_SYSCALLS,
    .sendsig = sendsig,
    /* .sigreturn / .rt_sigreturn deliberately left NULL.
     *
     * The arch-level fast path in arch/i386/syscall.c invokes
     * `p->sigreturn(regs)` directly with the kernel-side registers_t
     * pointer, which is the convention Linux/FreeBSD-style
     * sigreturn handlers need.  Substrate's native sys_sigreturn
     * takes a USER-SPACE sigcontext pointer (pushed by the
     * trampoline as the syscall arg), so it must go through the
     * normal syscall-table dispatch path where args[0] is extracted
     * from the user stack.  SYS_SIGRETURN / SYS_RT_SIGRETURN are
     * already mapped to sys_sigreturn / sys_rt_sigreturn in
     * native_syscalls[]. */
};
