/*
 * perso_openbsd.c - OpenBSD i386 Personality
 *
 * OpenBSD syscall numbers and wrappers for binary compatibility.
 * Based on OpenBSD i386 ABI.
 */

#include "personality.h"
#include "../../arch/i386/syscall.h"
#include <stddef.h>
#include <sys/syscall_impl.h>


/* OpenBSD syscall table - based on i386 column */
static void *openbsd_syscalls[MAX_SYSCALLS] = {
    [0] = NULL,             /* syscall (indirect) */
    [1] = &sys_exit,
    [2] = &sys_fork,
    [3] = &sys_read,
    [4] = &sys_write,
    [5] = &sys_open,
    [6] = &sys_close,
    [7] = &sys_waitpid,     /* wait4 */
    [8] = &sys_creat,
    [9] = &sys_link,
    [10] = &sys_unlink,
    [11] = NULL,            /* obs_execv */
    [12] = &sys_chdir,
    [13] = &sys_fchdir,
    [14] = &sys_mknod,
    [15] = &sys_chmod,
    [16] = NULL,            /* chown - not implemented */
    [17] = NULL,            /* break */
    [18] = NULL,            /* getfsstat */
    [19] = &sys_lseek,
    [20] = &sys_getpid,
    [21] = &sys_mount,
    [22] = &sys_umount,     /* unmount */
    [23] = &sys_setuid,
    [24] = &sys_getuid,
    [25] = &sys_geteuid,
    [26] = NULL,            /* ptrace - not implemented */
    [27] = NULL,            /* recvmsg */
    [28] = NULL,            /* sendmsg */
    [29] = NULL,            /* recvfrom */
    [30] = NULL,            /* accept */
    [31] = NULL,            /* getpeername */
    [32] = NULL,            /* getsockname */
    [33] = &sys_access,
    [34] = NULL,            /* chflags */
    [35] = NULL,            /* fchflags */
    [36] = &sys_sync,
    [37] = &sys_kill,
    [38] = &sys_stat,       /* compat_stat */
    [39] = &sys_getpid,     /* getppid */
    [40] = &sys_lstat,      /* compat_lstat */
    [41] = &sys_dup,
    [42] = &sys_pipe,
    [43] = &sys_getegid,
    [44] = NULL,            /* profil */
    [45] = NULL,            /* ktrace */
    [46] = &sys_sigaction,
    [47] = &sys_getgid,
    [48] = &sys_sigprocmask,
    [49] = NULL,            /* getlogin */
    [50] = NULL,            /* setlogin */
    [51] = &sys_acct,
    [52] = NULL,            /* sigpending */
    [53] = &sys_sigaltstack,
    [54] = &sys_ioctl,
    [55] = NULL,            /* reboot */
    [56] = NULL,            /* revoke */
    [57] = NULL,            /* symlink - not implemented */
    [58] = &sys_readlink,
    [59] = &sys_execve,
    [60] = NULL,            /* umask - not implemented */
    [61] = &sys_chroot,
    [62] = &sys_fstat,      /* compat_fstat */
    [63] = NULL,            /* compat_getkern */
    [64] = NULL,            /* getpagesize */
    [65] = NULL,            /* msync */
    [66] = &sys_vfork,
    [67] = NULL,            /* obs_vread */
    [68] = NULL,            /* obs_vwrite */
    [69] = NULL,            /* sbrk */
    [70] = NULL,            /* sstk */
    [71] = &sys_mmap,       /* compat_mmap */
    [72] = NULL,            /* vadvise */
    [73] = &sys_munmap,
    [74] = &sys_mprotect,
    [75] = NULL,            /* madvise */
    [76] = NULL,            /* obs_vhangup */
    [77] = NULL,            /* obs_vlimit */
    [78] = NULL,            /* mincore */
    [79] = NULL,            /* getgroups - not implemented */
    [80] = NULL,            /* setgroups - not implemented */
    [81] = &sys_getpgrp,
    [82] = &sys_setpgid,
    [83] = NULL,            /* setitimer */
    [84] = NULL,            /* compat_wait */
    [85] = NULL,            /* swapon */
    [86] = NULL,            /* getitimer */
    [87] = NULL,            /* gethostname */
    [88] = NULL,            /* sethostname */
    [89] = NULL,            /* getdtablesize */
    [90] = &sys_dup2,
    [91] = NULL,            /* reserved */
    [92] = NULL,            /* fcntl */
    [93] = NULL,            /* select */
    [94] = NULL,            /* reserved */
    [95] = NULL,            /* fsync */
    [96] = NULL,            /* setpriority */
    [97] = NULL,            /* socket */
    [98] = NULL,            /* connect */
    [99] = NULL,            /* compat_accept */
    [100] = NULL,           /* getpriority */
    [101] = NULL,           /* compat_send */
    [102] = NULL,           /* compat_recv */
    [103] = NULL,           /* compat_sigret */
    [104] = NULL,           /* bind */
    [105] = NULL,           /* setsockopt */
    [106] = NULL,           /* listen */
    [107] = NULL,           /* obs_vtimes */
    [108] = NULL,           /* compat_sigvec */
    [109] = NULL,           /* compat_sigblk */
    [110] = NULL,           /* compat_sigset */
    [111] = NULL,           /* sigsuspend */
    [112] = NULL,           /* compat_sigstk */
    [113] = NULL,           /* compat_recvmsg */
    [114] = NULL,           /* compat_sendmsg */
    [115] = NULL,           /* obs_vtrace */
    [116] = NULL,           /* gettimeofday */
    [117] = NULL,           /* getrusage */
    [118] = NULL,           /* getsockopt */
    [119] = NULL,           /* reserved */
    /* Higher syscalls - mapped separately per OpenBSD version */
};

static const char *openbsd_names[MAX_SYSCALLS] = {
    [0] = "syscall",
    [1] = "exit",
    [2] = "fork",
    [3] = "read",
    [4] = "write",
    [5] = "open",
    [6] = "close",
    [7] = "wait4",
    [8] = "creat",
    [9] = "link",
    [10] = "unlink",
    [11] = "obs_execv",
    [12] = "chdir",
    [13] = "fchdir",
    [14] = "mknod",
    [15] = "chmod",
    [16] = "chown",
    [17] = "break",
    [18] = "getfsstat",
    [19] = "lseek",
    [20] = "getpid",
    [21] = "mount",
    [22] = "unmount",
    [23] = "setuid",
    [24] = "getuid",
    [25] = "geteuid",
    [26] = "ptrace",
    [27] = "recvmsg",
    [28] = "sendmsg",
    [29] = "recvfrom",
    [30] = "accept",
    [31] = "getpeername",
    [32] = "getsockname",
    [33] = "access",
    [34] = "chflags",
    [35] = "fchflags",
    [36] = "sync",
    [37] = "kill",
    [38] = "compat_stat",
    [39] = "getppid",
    [40] = "compat_lstat",
    [41] = "dup",
    [42] = "pipe",
    [43] = "getegid",
    [46] = "sigaction",
    [47] = "getgid",
    [48] = "sigprocmask",
    [49] = "getlogin",
    [50] = "setlogin",
    [51] = "acct",
    [53] = "sigaltstack",
    [54] = "ioctl",
    [57] = "symlink",
    [58] = "readlink",
    [59] = "execve",
    [60] = "umask",
    [61] = "chroot",
    [62] = "compat_fstat",
    [66] = "vfork",
    [71] = "mmap",
    [73] = "munmap",
    [74] = "mprotect",
    [79] = "getgroups",
    [80] = "setgroups",
    [81] = "getpgrp",
    [82] = "setpgid",
    [90] = "dup2",
};

static struct syscall_fmt openbsd_fmts[MAX_SYSCALLS] = {
    [1] = { 1, { ARG_INT } },
    [3] = { 3, { ARG_INT, ARG_PTR, ARG_INT } },
    [4] = { 3, { ARG_INT, ARG_STR, ARG_INT } },
    [5] = { 3, { ARG_STR, ARG_HEX, ARG_HEX } },
    [6] = { 1, { ARG_INT } },
    [7] = { 3, { ARG_INT, ARG_PTR, ARG_INT } },
    [9] = { 2, { ARG_STR, ARG_STR } },
    [10] = { 1, { ARG_STR } },
    [12] = { 1, { ARG_STR } },
    [13] = { 1, { ARG_INT } },
    [14] = { 3, { ARG_STR, ARG_HEX, ARG_HEX } },
    [15] = { 2, { ARG_STR, ARG_HEX } },
    [16] = { 3, { ARG_STR, ARG_INT, ARG_INT } },
    [19] = { 3, { ARG_INT, ARG_INT, ARG_INT } },
    [21] = { 5, { ARG_STR, ARG_STR, ARG_STR, ARG_HEX, ARG_PTR } },
    [22] = { 1, { ARG_STR } },
    [23] = { 1, { ARG_INT } },
    [33] = { 2, { ARG_STR, ARG_HEX } },
    [37] = { 2, { ARG_INT, ARG_INT } },
    [38] = { 2, { ARG_STR, ARG_PTR } },
    [40] = { 2, { ARG_STR, ARG_PTR } },
    [41] = { 1, { ARG_INT } },
    [42] = { 1, { ARG_PTR } },
    [46] = { 3, { ARG_INT, ARG_PTR, ARG_PTR } },
    [48] = { 3, { ARG_INT, ARG_PTR, ARG_PTR } },
    [54] = { 3, { ARG_INT, ARG_HEX, ARG_HEX } },
    [57] = { 2, { ARG_STR, ARG_STR } },
    [58] = { 3, { ARG_STR, ARG_PTR, ARG_INT } },
    [59] = { 3, { ARG_STR, ARG_PTR, ARG_PTR } },
    [60] = { 1, { ARG_HEX } },
    [61] = { 1, { ARG_STR } },
    [90] = { 2, { ARG_INT, ARG_INT } },
};

struct personality personality_openbsd = {
    .name = "OpenBSD",
    .syscall_table = openbsd_syscalls,
    .syscall_names = openbsd_names,
    .syscall_fmts = openbsd_fmts,
    .syscall_count = MAX_SYSCALLS
};
