#include <exec/perso/personality.h>
#include <stddef.h>
#include <arch/i386/syscall.h>
#include <sys/syscall_impl.h>
#include <sys/resource.h>
#include <sys/times.h>
#include <include/sys/sysinfo.h>

extern int sys_mlock(const void *addr, size_t len);
extern int sys_munlock(const void *addr, size_t len);
extern int sys_setsid(void);
extern int sys_getsid(int pid);
extern int sys_setpgid(int pid, int pgid);
extern int sys_getpgid(int pid);
extern int sys_getrusage(int who, struct rusage *usage);
extern clock_t sys_times(void *buf);
extern int sys_stime(time_t *t);
extern int sys_ioctl(int fd, uint32_t request, void *arg);
extern int sys_ptrace(int req, int pid, int addr, int data);
extern int sys_reboot(int cmd);
extern int sys_sysctl(int *name, unsigned int namelen, void *oldp, size_t *oldlenp, void *newp, size_t newlen);
extern int sys_vm_stats(sys_vmstat_t *stats);
extern int sys_setpriority(int which, int who, int prio);
extern int sys_getpriority(int which, int who);

/* Native-specific syscalls are now in syscall_impl.h */

static void *native_syscalls[MAX_SYSCALLS] = {
    [SYS_EXIT] = &sys_exit,
    [SYS_FORK] = &sys_fork,
    [SYS_WAITPID] = &sys_waitpid,
    [SYS_POLL] = &sys_poll,
    [SYS_READ] = &sys_read,
    [SYS_WRITE] = &sys_write,
    [SYS_OPEN] = &sys_open,
    [SYS_CLOSE] = &sys_close,
    [SYS_EXECVE] = &sys_execve,
    [SYS_UNLINK] = (void*)sys_unlink,
    [SYS_TIME] = (void*)sys_time,
    [SYS_SIGRETURN] = (void*)sys_sigreturn,
    [SYS_SIGALTSTACK] = (void*)sys_sigaltstack,
    [SYS_LSEEK] = &sys_lseek,
    [SYS_STIME] = &sys_stime,
    [SYS_PTRACE] = &sys_ptrace,
    [SYS_GETPID] = &sys_getpid,
    [SYS_MOUNT] = &sys_mount,
    [SYS_UMOUNT] = &sys_umount,
    [SYS_SETUID] = &sys_setuid,
    [SYS_GETUID] = &sys_getuid,
    [SYS_ACCESS] = &sys_access,
    [SYS_SYNC] = &sys_sync,
    [SYS_KILL] = &sys_kill,
    [SYS_MKDIR] = &sys_mkdir,
    [SYS_RMDIR] = &sys_rmdir,
    [SYS_PIPE] = &sys_pipe,
    [SYS_SETGID] = &sys_setgid,
    [SYS_IOCTL] = &sys_ioctl,
    [SYS_GETGID] = &sys_getgid,
    [SYS_SIGNAL] = &sys_signal,
    [SYS_GETEUID] = &sys_geteuid,
    [SYS_GETEGID] = &sys_getegid,
    [SYS_ACCT] = &sys_acct,
    [SYS_DUP2] = &sys_dup2,
    [SYS_STAT] = &sys_stat,
    [SYS_LSTAT] = &sys_lstat,
    [SYS_FSTAT] = &sys_fstat,
    [SYS_UNAME] = &sys_uname,
    [SYS_MODIFY_LDT] = &sys_modify_ldt,
    [SYS_READLINK] = &sys_readlink,
    [SYS_REBOOT] = &sys_reboot,
    [SYS_MMAP] = &sys_mmap,
    [SYS_GETDENTS] = &sys_getdents, 
    [SYS_MSYNC] = &sys_msync,
    [SYS_NANOSLEEP] = &sys_nanosleep,
    [SYS_GETCWD] = &sys_getcwd,
    [SYS_PMAP_STATS] = &sys_pmap_stats,
    [SYS_THR_SELF] = &sys_thr_self,
    [SYS_THR_NEW] = &sys_thr_new,
    [SYS_THR_EXIT] = &sys_thr_exit,
    [SYS_THR_JOIN] = &sys_thr_join,
    [SYS_PROC_INFO] = &sys_proc_info,
    [SYS_PROC_LIST] = &sys_proc_list,
    [SYS_PROC_COUNT] = &sys_proc_count,
    [SYS_CPU_COUNT] = &sys_cpu_count,
    [SYS_HOSTNAME] = &sys_hostname,
    [SYS_GETPPID] = &sys_getppid,
    [SYS_SIGACTION] = (void*)sys_sigaction,
    [SYS_SIGPROCMASK] = (void*)sys_sigprocmask,
    [SYS_SIGPENDING] = (void*)sys_sigpending,
    [SYS_SIGSUSPEND] = (void*)sys_sigsuspend,
    [SYS_RT_SIGRETURN] = (void*)sys_rt_sigreturn,
    [SYS_SYSCTL] = &sys_sysctl,
    [SYS_SYSINFO] = &sys_sysinfo,
    [SYS_mlock] = &sys_mlock,
    [SYS_munlock] = &sys_munlock,
    [SYS_SETSID] = &sys_setsid,
    [SYS_GETSID] = &sys_getsid,
    [SYS_SETPGID] = &sys_setpgid,
    [SYS_GETPGID] = &sys_getpgid,
    [SYS_GETRUSAGE] = &sys_getrusage,
    [SYS_TIMES] = &sys_times,
    [SYS_PROC_THREADS] = &sys_proc_threads,
    [SYS_PROC_FDS] = &sys_proc_fds,
    [SYS_PROC_MAPS] = &sys_proc_maps,
    [SYS_PROC_CWD] = &sys_proc_cwd,
    [SYS_PROC_EXE] = &sys_proc_exe,
    [SYS_PROC_CMDLINE] = &sys_proc_cmdline,
    [SYS_PROC_ENVIRON] = &sys_proc_environ,
    [SYS_VM_STATS] = &sys_vm_stats,
    [SYS_SETPRIORITY] = &sys_setpriority,
    [SYS_GETPRIORITY] = &sys_getpriority,
};

static const char *native_names[MAX_SYSCALLS] = {
    [SYS_EXIT] = "exit",
    [SYS_FORK] = "fork",
    [SYS_WAITPID] = "waitpid",
    [SYS_POLL] = "poll",
    [SYS_READ] = "read",
    [SYS_WRITE] = "write",
    [SYS_OPEN] = "open",
    [SYS_CLOSE] = "close",
    [SYS_EXECVE] = "execve",
    [SYS_UNLINK] = "unlink",
    [SYS_TIME] = "time",
    [SYS_LSEEK] = "lseek",
    [SYS_STIME] = "stime",
    [SYS_PTRACE] = "ptrace",
    [SYS_GETPID] = "getpid",
    [SYS_MOUNT] = "mount",
    [SYS_UMOUNT] = "umount",
    [SYS_SETUID] = "setuid",
    [SYS_GETUID] = "getuid",
    [SYS_ACCESS] = "access",
    [SYS_SYNC] = "sync",
    [SYS_KILL] = "kill",
    [SYS_MKDIR] = "mkdir",
    [SYS_RMDIR] = "rmdir",
    [SYS_PIPE] = "pipe",
    [SYS_SETGID] = "setgid",
    [SYS_IOCTL] = "ioctl",
    [SYS_GETGID] = "getgid",
    [SYS_SIGNAL] = "signal",
    [SYS_GETEUID] = "geteuid",
    [SYS_GETEGID] = "getegid",
    [SYS_ACCT] = "acct",
    [SYS_DUP2] = "dup2",
    [SYS_READLINK] = "readlink",
    [SYS_REBOOT] = "reboot",
    [SYS_STAT] = "stat",
    [SYS_LSTAT] = "lstat",
    [SYS_FSTAT] = "fstat",
    [SYS_SIGRETURN] = "sigreturn",
    [SYS_UNAME] = "uname",
    [SYS_MODIFY_LDT] = "modify_ldt",
    [SYS_GETDENTS] = "getdents",
    [SYS_MSYNC] = "msync",
    [SYS_NANOSLEEP] = "nanosleep",
    [SYS_GETCWD] = "getcwd",
    [SYS_SIGALTSTACK] = "sigaltstack",
    [SYS_PMAP_STATS] = "pmap_stats",
    [SYS_THR_SELF] = "thr_self",
    [SYS_THR_NEW] = "thr_new",
    [SYS_THR_EXIT] = "thr_exit",
    [SYS_THR_JOIN] = "thr_join",
    [SYS_PROC_INFO] = "proc_info",
    [SYS_PROC_LIST] = "proc_list",
    [SYS_PROC_COUNT] = "proc_count",
    [SYS_CPU_COUNT] = "cpu_count",
    [SYS_HOSTNAME] = "hostname",
    [SYS_GETPPID] = "getppid",
    [SYS_SIGACTION] = "sigaction",
    [SYS_SIGPROCMASK] = "sigprocmask",
    [SYS_SIGPENDING] = "sigpending",
    [SYS_SIGSUSPEND] = "sigsuspend",
    [SYS_RT_SIGRETURN] = "rt_sigreturn",
    [SYS_SYSCTL] = "sysctl",
    [SYS_SYSINFO] = "sysinfo",
    [SYS_mlock] = "mlock",
    [SYS_munlock] = "munlock",
    [SYS_SETSID] = "setsid",
    [SYS_GETSID] = "getsid",
    [SYS_SETPGID] = "setpgid",
    [SYS_GETPGID] = "getpgid",
    [SYS_GETRUSAGE] = "getrusage",
    [SYS_TIMES] = "times",
    [SYS_PROC_THREADS] = "proc_threads",
    [SYS_PROC_FDS] = "proc_fds",
    [SYS_PROC_MAPS] = "proc_maps",
    [SYS_PROC_CWD] = "proc_cwd",
    [SYS_PROC_EXE] = "proc_exe",
    [SYS_PROC_CMDLINE] = "proc_cmdline",
    [SYS_PROC_ENVIRON] = "proc_environ",
    [SYS_VM_STATS] = "vm_stats",
    [SYS_SETPRIORITY] = "setpriority",
    [SYS_GETPRIORITY] = "getpriority",
};

static struct syscall_fmt native_fmts[MAX_SYSCALLS] = {
    [SYS_EXIT] = { 1, { ARG_INT } },
    [SYS_FORK] = { 0, { 0 } },
    [SYS_WAITPID] = { 3, { ARG_INT, ARG_PTR, ARG_INT } },
    [SYS_READ] = { 3, { ARG_INT, ARG_PTR, ARG_INT } },
    [SYS_WRITE] = { 3, { ARG_INT, ARG_STR, ARG_INT } },
    [SYS_OPEN] = { 3, { ARG_STR, ARG_HEX, ARG_HEX } },
    [SYS_CLOSE] = { 1, { ARG_INT } },
    [SYS_EXECVE] = { 3, { ARG_STR, ARG_PTR, ARG_PTR } },
    [SYS_UNLINK] = { 1, { ARG_STR } },
    [SYS_TIME] = { 1, { ARG_PTR } },
    [SYS_SIGRETURN] = { 1, { ARG_PTR } },
    [SYS_SIGALTSTACK] = { 2, { ARG_PTR, ARG_PTR } },
    [SYS_LSEEK] = { 4, { ARG_INT, ARG_HEX, ARG_HEX, ARG_INT } },
    [SYS_STIME] = { 1, { ARG_PTR } },
    [SYS_PTRACE] = { 4, { ARG_INT, ARG_INT, ARG_PTR, ARG_INT } },
    [SYS_GETPID] = { 0, { 0 } },
    [SYS_MOUNT] = { 5, { ARG_STR, ARG_STR, ARG_STR, ARG_HEX, ARG_PTR } },
    [SYS_UMOUNT] = { 1, { ARG_STR } },
    [SYS_SETUID] = { 1, { ARG_INT } },
    [SYS_GETUID] = { 0, { 0 } },
    [SYS_ACCESS] = { 2, { ARG_STR, ARG_HEX } },
    [SYS_SYNC] = { 0, { 0 } },
    [SYS_KILL] = { 2, { ARG_INT, ARG_INT } },
    [SYS_MKDIR] = { 2, { ARG_STR, ARG_HEX } },
    [SYS_RMDIR] = { 1, { ARG_STR } },
    [SYS_PIPE] = { 1, { ARG_PTR } },
    [SYS_SETGID] = { 1, { ARG_INT } },
    [SYS_IOCTL] = { 3, { ARG_INT, ARG_HEX, ARG_HEX } },
    [SYS_GETGID] = { 0, { 0 } },
    [SYS_SIGNAL] = { 2, { ARG_INT, ARG_PTR } },
    [SYS_GETEUID] = { 0, { 0 } },
    [SYS_GETEGID] = { 0, { 0 } },
    [SYS_ACCT] = { 1, { ARG_STR } },
    [SYS_DUP2] = { 2, { ARG_INT, ARG_INT } },
    [SYS_READLINK] = { 3, { ARG_STR, ARG_PTR, ARG_INT } },
    [SYS_REBOOT] = { 1, { ARG_INT } },
    [SYS_STAT] = { 2, { ARG_STR, ARG_PTR } },
    [SYS_LSTAT] = { 2, { ARG_STR, ARG_PTR } },
    [SYS_FSTAT] = { 2, { ARG_INT, ARG_PTR } },
    [SYS_UNAME] = { 1, { ARG_PTR } },
    [SYS_MODIFY_LDT] = { 3, { ARG_INT, ARG_PTR, ARG_LONG } },
    [SYS_GETDENTS] = { 3, { ARG_INT, ARG_PTR, ARG_INT } },
    [SYS_MSYNC] = { 3, { ARG_PTR, ARG_INT, ARG_INT } },
    [SYS_NANOSLEEP] = { 2, { ARG_PTR, ARG_PTR } },
    [SYS_GETCWD] = { 2, { ARG_PTR, ARG_INT } },
    [SYS_POLL] = { 3, { ARG_PTR, ARG_INT, ARG_INT } },
    [SYS_PMAP_STATS] = { 1, { ARG_PTR } },
    [SYS_THR_SELF] = { 0, { 0 } },
    [SYS_THR_NEW] = { 2, { ARG_PTR, ARG_INT } },
    [SYS_THR_EXIT] = { 1, { ARG_PTR } },
    [SYS_THR_JOIN] = { 2, { ARG_INT, ARG_PTR } },
    [SYS_PROC_INFO] = { 2, { ARG_INT, ARG_PTR } },
    [SYS_PROC_LIST] = { 2, { ARG_PTR, ARG_INT } },
    [SYS_PROC_COUNT] = { 0, { 0 } },
    [SYS_CPU_COUNT] = { 0, { 0 } },
    [SYS_HOSTNAME] = { 2, { ARG_PTR, ARG_INT } },
    [SYS_GETPPID] = { 0, { 0 } },
    [SYS_SIGACTION] = { 3, { ARG_INT, ARG_PTR, ARG_PTR } },
    [SYS_SIGPROCMASK] = { 3, { ARG_INT, ARG_PTR, ARG_PTR } },
    [SYS_SIGPENDING] = { 1, { ARG_PTR } },
    [SYS_SIGSUSPEND] = { 1, { ARG_PTR } },
    [SYS_RT_SIGRETURN] = { 1, { ARG_PTR } },
    [SYS_SYSCTL] = { 6, { ARG_PTR, ARG_INT, ARG_PTR, ARG_PTR, ARG_PTR, ARG_INT } },
    [SYS_SYSINFO] = { 1, { ARG_PTR } },
    [SYS_mlock] = { 2, { ARG_PTR, ARG_INT } },
    [SYS_munlock] = { 2, { ARG_PTR, ARG_INT } },
    [SYS_SETSID] = { 0, { 0 } },
    [SYS_GETSID] = { 1, { ARG_INT } },
    [SYS_SETPGID] = { 2, { ARG_INT, ARG_INT } },
    [SYS_GETPGID] = { 1, { ARG_INT } },
    [SYS_GETRUSAGE] = { 2, { ARG_INT, ARG_PTR } },
    [SYS_TIMES] = { 1, { ARG_PTR } },
    [SYS_PROC_THREADS] = { 3, { ARG_INT, ARG_PTR, ARG_PTR } },
    [SYS_PROC_FDS] = { 3, { ARG_INT, ARG_PTR, ARG_PTR } },
    [SYS_PROC_MAPS] = { 3, { ARG_INT, ARG_PTR, ARG_PTR } },
    [SYS_PROC_CWD] = { 3, { ARG_INT, ARG_PTR, ARG_INT } },
    [SYS_PROC_EXE] = { 3, { ARG_INT, ARG_PTR, ARG_INT } },
    [SYS_PROC_CMDLINE] = { 3, { ARG_INT, ARG_PTR, ARG_PTR } },
    [SYS_PROC_ENVIRON] = { 3, { ARG_INT, ARG_PTR, ARG_PTR } },
    [SYS_VM_STATS] = { 1, { ARG_PTR } },
    [SYS_SETPRIORITY] = { 3, { ARG_INT, ARG_INT, ARG_INT } },
    [SYS_GETPRIORITY] = { 2, { ARG_INT, ARG_INT } },
};

extern void sendsig(void *handler, int sig, uint32_t mask, uint32_t flags, void *regs);
extern int sys_sigreturn(void *regs);
extern int sys_rt_sigreturn(void *regs);

struct personality personality_native = {
    .name = "substrate",
    .id = PERS_NATIVE,
    .syscall_table = native_syscalls,
    .syscall_names = native_names,
    .syscall_fmts = native_fmts,
    .syscall_count = MAX_SYSCALLS,
    .sendsig = sendsig,
    .sigreturn = sys_sigreturn,
    .rt_sigreturn = sys_rt_sigreturn
};
