#!/bin/sh
# /etc/rc.d/10-loopback — bring up the loopback interface.

case "${1:-start}" in
    start)
        /sbin/ifconfig lo up
        ;;
    stop)
        /sbin/ifconfig lo down
        ;;
    status)
        /sbin/ifconfig lo
        ;;
    restart)
        $0 stop
        $0 start
        ;;
esac
