/*
 * bench_idle.c - Host-side benchmark for idle loop switch
 *
 * To run this benchmark, use the provided run_bench_idle.sh script.
 * It copies and modifies sys/kern/swapper.c to be compiled standalone.
 */

#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>

// Mock definitions
#define AC_COMM_LEN 16
#define THREAD_RUNNING 1
#define THREAD_READY 2
#define THREAD_BLOCKED 3
#define THREAD_ZOMBIE 4
#define SCHED_IDLE 0
#define SCHED_TIMESHARE 1

typedef struct process {
    int pid;
    int ppid;
    void *p_pgrp; // Mock pointer
    // int session; // Removed to match kernel struct
    int is_kernel_task;
    char comm[AC_COMM_LEN];
} process_t;

typedef struct thread {
    int tid;
    process_t *proc;
    int state;
    int sched_class;
    int priority;
    int base_priority;
    int needs_resched;
} thread_t;

// Globals used by swapper.c
thread_t *current_thread = NULL;
process_t *current_process = NULL;

// Externs declared in swapper.c
void vm_pageout_daemon(void) {}
void uma_reclaim(void) {}

// Scheduler functions used in swapper.c
thread_t *next_thread_to_return = NULL;

thread_t *sched_idle_balance(void) {
    return next_thread_to_return;
}

// Global thread list for O(N) yield simulation
#define MAX_THREADS 64
thread_t threads[MAX_THREADS];

void sched_yield(void) {
    // Simulate O(N) scan
    thread_t *best = NULL;
    for (int i = 0; i < MAX_THREADS; i++) {
        if (threads[i].tid != -1 && threads[i].state == THREAD_READY) {
            // Simulate work (memory access + loop overhead)
            __asm__ volatile("nop");
            best = &threads[i];
        }
    }
    if (best) {
        // Switch logic (simulated)
        if (current_thread && current_thread->state == THREAD_RUNNING) current_thread->state = THREAD_READY;
        current_thread = best;
        current_thread->state = THREAD_RUNNING;
    }
}

// Function to compile against - generated by script
#include "swapper_mock.c"

// New function we will add later (simulated here for comparison)
void sched_switch(thread_t *next) {
    if (current_thread && current_thread->state == THREAD_RUNNING) current_thread->state = THREAD_READY;
    current_thread = next;
    current_thread->state = THREAD_RUNNING;
}

// Modified swapper loop for optimized version (manual inline of sched_switch logic)
void swapper_idle_loop_optimized(void) {
    for (int i = 0; i < 1; i++) { // Run once
        // 1. Check for work to do (skipped here as idle_work_pending is 0)

        // 2. Try to find runnable thread
        thread_t *next = sched_idle_balance();
        if (next) {
            // Optimization: Switch directly
            if (current_thread && current_thread->state == THREAD_RUNNING) current_thread->state = THREAD_READY;
            current_thread = next;
            current_thread->state = THREAD_RUNNING;
            continue;
        }
    }
}


int main() {
    // Setup environment
    swapper_init();

    // Setup target thread
    process_t p;
    thread_t t;
    memset(&t, 0, sizeof(t));
    t.tid = 1;
    t.proc = &p;
    t.state = THREAD_READY;

    // Put target thread in global list for sched_yield
    memset(threads, 0, sizeof(threads));
    for(int i=0; i<MAX_THREADS; i++) threads[i].tid = -1;
    threads[1] = t;

    // Set next thread for balance
    next_thread_to_return = &threads[1];

    // Measure Baseline (swapper_idle_loop calls sched_yield)
    // Note: swapper_idle_loop is compiled from swapper_mock.c which has the ORIGINAL code (calls sched_yield)

    clock_t start = clock();
    for (int i = 0; i < 1000000; i++) {
        // Reset state
        current_thread = swapper_get_idle_thread();
        current_thread->state = THREAD_RUNNING;
        threads[1].state = THREAD_READY;

        swapper_idle_loop();
    }
    clock_t end = clock();
    double time_baseline = (double)(end - start) / CLOCKS_PER_SEC;

    printf("Baseline Time: %f seconds\n", time_baseline);

    // Measure Optimized
    start = clock();
    for (int i = 0; i < 1000000; i++) {
        // Reset state
        current_thread = swapper_get_idle_thread();
        current_thread->state = THREAD_RUNNING;
        threads[1].state = THREAD_READY;

        swapper_idle_loop_optimized();
    }
    end = clock();
    double time_optimized = (double)(end - start) / CLOCKS_PER_SEC;

    printf("Optimized Time: %f seconds\n", time_optimized);
    if (time_baseline > 0)
        printf("Improvement: %.2f%%\n", (time_baseline - time_optimized) / time_baseline * 100.0);
    else
        printf("Improvement: Infinite\n");

    return 0;
}
