#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <assert.h>

// Include the source under test
// This file is generated by the test runner script to fix include paths
#include "kobject_under_test.c"

int release_called = 0;
struct kobject *released_obj = NULL;

void my_release(struct kobject *kobj) {
    release_called++;
    released_obj = kobj;
    printf("Release called for %s\n", kobj->name);
}

int main() {
    struct kobject kobj;

    // Ensure memory is dirty before init to test zeroing
    memset(&kobj, 0xAA, sizeof(kobj));

    kobject_init(&kobj, "test_obj");

    // Test initialization
    if (kobj.refcount != 1) {
        printf("FAIL: Initial refcount should be 1, got %u\n", kobj.refcount);
        return 1;
    }
    if (kobj.release != NULL) {
        printf("FAIL: Initial release callback should be NULL\n");
        return 1;
    }
    if (strcmp(kobj.name, "test_obj") != 0) {
        printf("FAIL: Name mismatch, got %s\n", kobj.name);
        return 1;
    }

    // Set release callback
    kobj.release = my_release;

    // Test get
    kobject_get(&kobj);
    if (kobj.refcount != 2) {
        printf("FAIL: Refcount after get should be 2, got %u\n", kobj.refcount);
        return 1;
    }

    // Test put (refcount 2 -> 1, no release)
    kobject_put(&kobj);
    if (kobj.refcount != 1) {
        printf("FAIL: Refcount after first put should be 1, got %u\n", kobj.refcount);
        return 1;
    }
    if (release_called != 0) {
        printf("FAIL: Release callback called prematurely\n");
        return 1;
    }

    // Test put (refcount 1 -> 0, release called)
    kobject_put(&kobj);
    if (kobj.refcount != 0) {
        printf("FAIL: Refcount after final put should be 0, got %u\n", kobj.refcount);
        return 1;
    }
    if (release_called != 1) {
        printf("FAIL: Release callback not called\n");
        return 1;
    }
    if (released_obj != &kobj) {
        printf("FAIL: Release callback called with wrong object\n");
        return 1;
    }

    // Test with NULL release
    struct kobject kobj2;
    kobject_init(&kobj2, "test_obj2");
    kobject_put(&kobj2); // Should not crash
    if (kobj2.refcount != 0) {
        printf("FAIL: Refcount for kobj2 should be 0, got %u\n", kobj2.refcount);
        return 1;
    }

    printf("All tests passed!\n");
    return 0;
}
