.Dd October 26, 2023
.Dt AR 1
.Os Substrate
.Sh NAME
.Nm ar
.Nd archive utility
.Sh SYNOPSIS
.Nm
.Op Fl cDrstuvx
.Op Ar archive
.Op Ar member ...
.Sh DESCRIPTION
The
.Nm
utility creates, modifies, and extracts from archives.
An archive is a single file holding a collection of other files in a structure that makes it possible to retrieve the original individual files (called members).
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c
Create the archive if it does not exist.
.It Fl d
Delete the specified members from the archive.
.It Fl m
Move the specified members.
.It Fl p
Print the specified members to standard output.
.It Fl q
Quickly append the specified members to the archive.
.It Fl r
Replace or add the specified members to the archive.
.It Fl s
Write an object-file index into the archive, or update an existing one, even if no other change is made to the archive.
.It Fl t
List the specified members.
.It Fl u
Only update members if the file is newer than the archive member.
.It Fl v
Verbose mode.
.It Fl x
Extract the specified members.
.El
.Sh COMPATIBILITY
The
.Nm
utility supports the BSD archive format with
.Dq #1/len
extended filenames.
It generates a BSD-style
.Dq __.SYMDEF
symbol table for ELF object files.
.Sh SEE ALSO
.Xr ranlib 1 ,
.Xr ld 1
