.TH demangle_version 3 "February 2026" "Substrate" "Library Functions"
.SH NAME
demangle_version \- return libdemangle version string
.SH SYNOPSIS
.nf
.B #include <demangle.h>
.PP
.BI "const char *demangle_version(void);"
.fi
.SH LIBRARY
libdemangle (\fI-l:libdemangle.a\fR)
.SH DESCRIPTION
.B demangle_version()
returns a constant NUL-terminated string describing the library version.
The returned pointer must not be freed.
.SH RETURN VALUE
Pointer to a static version string.
.SH SEE ALSO
.BR demangle (3)
