#!/bin/sh
#
# contrib/cde/fetch.sh — fetch the Common Desktop Environment (cdesktopenv)
# source, apply the substrate patch series, and prepare the autotools build.
#
# CDE is a git repository, not a release tarball, so instead of a
# SHA256-verified download the source is PINNED to an exact upstream commit
# (COMMIT below) on the C23-GCC15-Changes branch — substrate's toolchain is
# GCC 16 and the 30-year-old CDE sources need that branch's modern-compiler
# fixes to build at all.  The modern cdesktopenv build is autotools
# (autogen.sh + configure + make); imake is no longer used.
#
# Order matters: the patch series is applied to the pristine tree BEFORE
# autogen.sh, so automake regenerates Makefile.in from the patched
# Makefile.am; the config.sub/configure adjustments afterwards are seds
# because those files are GENERATED by autogen.sh (a patch can't target
# them reproducibly).
#
# This only prepares the source tree; build.sh drives the cross-build.

set -eu

BRANCH="C23-GCC15-Changes"
COMMIT="68cae0c36b5caccb3e00b5371f4031147154acf9"
REPO="https://git.code.sf.net/p/cdesktopenv/code"

HERE="$(cd "$(dirname "$0")" && pwd)"
BUILD_DIR="${HERE}/build"
TREE_DIR="${BUILD_DIR}/cdesktopenv"

mkdir -p "${BUILD_DIR}"

if [ ! -d "${TREE_DIR}/.git" ]; then
    [ "${1:-}" = "--no-network" ] && { echo "fetch.sh: source tree missing" >&2; exit 1; }
    echo "==> Cloning CDE (${BRANCH}) — this is a large checkout"
    git clone --depth 1 --branch "${BRANCH}" "${REPO}" "${TREE_DIR}"
fi

# Pin: make sure we are building exactly COMMIT, not wherever the branch
# has moved.  If the clone's HEAD is not the pin, fetch the pinned commit
# explicitly and check it out (detached).
cur=$(git -C "${TREE_DIR}" rev-parse HEAD)
if [ "${cur}" != "${COMMIT}" ]; then
    echo "==> Branch head ${cur} != pinned ${COMMIT}; fetching the pin"
    git -C "${TREE_DIR}" fetch --depth 1 origin "${COMMIT}"
    git -C "${TREE_DIR}" checkout --detach "${COMMIT}"
fi
echo "==> CDE source at pinned commit ${COMMIT}"

CDE="${TREE_DIR}/cde"
[ -d "${CDE}" ] || { echo "fetch.sh: ${CDE} missing after clone" >&2; exit 1; }

# --- substrate patch series (against the pristine pinned tree) -----------
if [ -f "${HERE}/series" ]; then
    cd "${TREE_DIR}"
    while IFS= read -r p; do
        case "$p" in ''|'#'*) continue ;; esac
        [ -f "${HERE}/patches/${p}" ] || { echo "fetch.sh: missing patch ${p}" >&2; exit 1; }
        if patch -p1 --dry-run -s -R < "${HERE}/patches/${p}" >/dev/null 2>&1; then echo "==> ${p} already applied"; continue; fi
        echo "==> Applying ${p}"; patch -p1 < "${HERE}/patches/${p}"
    done < "${HERE}/series"
fi

echo "==> autogen.sh (generate configure)"
( cd "${CDE}" && ./autogen.sh )

# --- substrate adjustments to the GENERATED autotools files --------------
# config.sub: accept the substrate OS triple.
if ! grep -q 'substrate\*' "${CDE}/config.sub"; then
    echo "==> patching config.sub for substrate"
    sed -i 's/\(\t| sunos \\\)/\t| substrate* \\\n\1/' "${CDE}/config.sub"
fi
# libtool (generated configure): treat substrate* like linux* for shared libs.
if ! grep -q 'substrate\*' "${CDE}/configure"; then
    echo "==> patching libtool host_os cases for substrate"
    sed -i \
      -e 's@linux\* | k\*bsd\*-gnu | kopensolaris\*-gnu | gnu\*)@linux* | k*bsd*-gnu | kopensolaris*-gnu | gnu* | substrate*)@g' \
      -e 's@gnu\* | linux\* | tpf\* | k\*bsd\*-gnu | kopensolaris\*-gnu)@gnu* | linux* | tpf* | k*bsd*-gnu | kopensolaris*-gnu | substrate*)@g' \
      -e 's@^\(\s*\)linux\*)@\1linux* | substrate*)@g' \
      "${CDE}/configure"
fi

echo "==> CDE source ready at ${CDE}"
