.Dd January 29, 2026
.Dt DC 1
.Os Substrate
.Sh NAME
.Nm dc
.Nd arbitrary precision desk calculator
.Sh SYNOPSIS
.Nm
.Op Fl h
.Sh DESCRIPTION
.Nm
is an arbitrary precision desk calculator that uses Reverse Polish Notation (RPN).
It operates on a stack of arbitrary precision numbers.
.Sh EXTENSIONS
.Nm
implements the following GNU extensions:
.Bl -tag -width "Comments"
.It Comments
Support for
.Li #
characters to start a comment that extends to the end of the line.
.It Output
The
.Li n
command prints the value at the top of the stack without a trailing newline, popping it from the stack.
.El
.Sh SEE ALSO
.Xr bc 1
.Sh HISTORY
This implementation of
.Nm
was written for the Substrate operating system.
.Sh AUTHORS
.An Segin
