.TH ID 1 "March 2026" "Substrate" "User Commands"
.SH NAME
id \- return user identity
.SH SYNOPSIS
.B id
.RB [ user ]
.br
.B id \-G
.RB [ \-n ]
.RB [ user ]
.br
.B id \-g
.RB [ \-nr ]
.RB [ user ]
.br
.B id \-u
.RB [ \-nr ]
.RB [ user ]
.br
.B id
.RB [ \-pPcdsAMR ]
.RB [ user ]
.br
.B id
.RB [ \-\-zero ]
.RB [ \-\-context ]
.RB [ user... ]
.SH DESCRIPTION
The
.B id
utility writes information about the current user or a specified
.IR user .
By default, the utility writes the user name, user ID, group name, group ID,
and supplementary group information of the current or specified user.
.SH OPTIONS
The following options are supported:
.TP
.BR \-A
Output the process audit user ID and audit properties (FreeBSD extension).
.TP
.BR \-c
Output the login class (BSD extension).
.TP
.BR \-d
Output the home directory of the current or specified user (FreeBSD extension).
.TP
.BR \-G ", " \-\-groups
Output all different group IDs (effective, real, and supplementary).
.TP
.BR \-g ", " \-\-group
Output only the effective group ID.
.TP
.BR \-M
Output the MAC label of the current process (FreeBSD extension).
.TP
.BR \-n ", " \-\-name
Output the name in the format specified by the
.B \-u
or
.B \-g
or
.B \-G
options instead of the numeric ID. If the ID cannot be mapped to a name, the numeric value is printed.
.TP
.BR \-p
Make the output human-readable, emitting keywords on separate lines (BSD extension).
.TP
.BR \-P
Output a passwd(5)-style entry for the specified user (FreeBSD extension).
.TP
.BR \-R
Output the routing table of the current process (OpenBSD extension).
.TP
.BR \-r ", " \-\-real
Output the real ID instead of the effective ID for the
.B \-u
or
.B \-g
options.
.TP
.BR \-s
Output the login shell of the current or specified user (FreeBSD extension).
.TP
.BR \-u ", " \-\-user
Output only the effective user ID.
.TP
.BR \-Z ", " \-\-context
Print only the security context of the process (GNU extension).
.TP
.BR \-z ", " \-\-zero
Delimit output with NUL characters instead of whitespace (GNU extension).
.SH EXIT STATUS
The
.B id
utility returns 0 on success, and >0 if an error occurs.
.SH SEE ALSO
getgroups(2), getgid(2), getuid(2), passwd(5)
