.Dd March 2, 2026
.Dt ELF_LINK_PLAN_SET_GC_HOOK 3
.Os
.Sh NAME
.Nm elf_link_plan_set_gc_hook
.Nd install section garbage-collection policy callback for a link plan
.Sh LIBRARY
libelfobj
.Sh SYNOPSIS
.In elfobj.h
.Ft elf_err_t
.Fn elf_link_plan_set_gc_hook "elf_link_plan_t *plan" "elf_link_gc_hook_t hook" "void *user"
.Sh DESCRIPTION
Associates GC policy callback and user context with
.Fa plan .
.Sh RETURN VALUES
Returns
.Dv ELF_OK
on success, otherwise
.Dv ELF_ERR_STATE .
.Sh SEE ALSO
.Xr elf_link_plan_link 3
