.TH GETERROR 3 2026-04-06 "Substrate LibC" "Substrate Library Functions"
.SH NAME
geterror \- return string describing error number
.SH SYNOPSIS
.B #include <string.h>
.sp
.BI "char *geterror(int " errnum ");"
.SH DESCRIPTION
The
.BR geterror ()
function returns a pointer to a string describing the error code passed in
.IR errnum .
It is a Substrate compatibility alias for
.BR strerror (3).
.SH RETURN VALUE
The
.BR geterror ()
function returns a pointer to a static error description string. If
.IR errnum
is unknown, it returns
.BR "Unknown error" .
.SH EXAMPLES
The following program prints the description of an error code.
.PP
.RS 4
.EX
#include <string.h>
#include <stdio.h>

int
main(void)
{
    printf("%s\en", geterror(2));
    return 0;
}
.EE
.RE
.SH SEE ALSO
.BR errno (3),
.BR perror (3),
.BR strerror (3)
