.\"
.\" PTHREAD_EXIT(3) - Substrate Pthreads Library
.\"
.TH PTHREAD_EXIT 3 "January 2026" "Substrate OS" "Library Functions"
.SH NAME
pthread_exit \- terminate calling thread
.SH SYNOPSIS
.nf
.B #include <pthread.h>
.PP
.BI "void pthread_exit(void *" retval ");
.fi
.SH DESCRIPTION
The
.BR pthread_exit ()
function terminates the calling thread and returns a value via
.I retval
that (if the thread is joinable) is available to another thread in the same
process that calls
.BR pthread_join (3).
.SH RETURN VALUE
This function does not return to the caller.
.SH SEE ALSO
.BR pthread_create (3),
.BR pthread_join (3),
.BR thr_exit (2)
