.\"
.\" PTHREAD_EXIT(3) - Substrate Pthreads Library
.\"
.TH PTHREAD_EXIT 3 "January 2026" "Substrate OS" "Library Functions"
.SH NAME
pthread_exit \- terminate calling thread
.SH SYNOPSIS
.nf
.B #include <pthread.h>
.PP
.BI "void pthread_exit(void *" retval ");
.fi
.SH DESCRIPTION
The
.BR pthread_exit ()
function terminates the calling thread and returns a value via
.I retval
that (if the thread is joinable) is available to another thread in the same
process that calls
.BR pthread_join (3).
.SH RETURN VALUE
This function does not return to the caller.
.SH EXAMPLES
A thread returns a result to its joiner via
.BR pthread_exit ().
.PP
.RS 4
.EX
#include <pthread.h>
#include <stdio.h>

static void *
worker(void *arg)
{
    (void)arg;
    pthread_exit((void *)42);
}

int
main(void)
{
    pthread_t t;
    void *ret;

    pthread_create(&t, NULL, worker, NULL);
    pthread_join(t, &ret);
    printf("worker returned %ld\en", (long)ret);
    return 0;
}
.EE
.RE
.SH SEE ALSO
.BR pthread_create (3),
.BR pthread_join (3),
.BR thr_exit (2)
