.TH TAN 3 "2026-05-03" "Substrate" "Library Functions Manual"
.SH NAME
tan, tanf, tanl \- tangent function
.SH LIBRARY
Math Library (libm, \-lm)
.SH SYNOPSIS
.B #include <math.h>
.PP
.B double tan(double x);
.B float tanf(float x);
.B long double tanl(long double x);
.SH DESCRIPTION
The
.B tan()
function computes the tangent of
.IR x ,
where
.I x
is expressed in radians.
.PP
The
.B tanf()
and
.B tanl()
functions are float and long double variants respectively.
.SH RETURN VALUE
The function returns the tangent of
.IR x .
.PP
If x is infinity, +infinity is returned.
.PP
If x is NaN, NaN is returned.
.SH EXAMPLES
Compute the tangent of an angle expressed in radians.
.PP
.RS 4
.EX
#include <math.h>
#include <stdio.h>

int
main(void)
{
    double x = M_PI / 4.0;

    printf("tan(pi/4) = %.6f\en", tan(x));
    return 0;
}
.EE
.RE
.SH STANDARDS
C99, POSIX.1-2001.
.SH SEE ALSO
.BR sin (3),
.BR cos (3),
.BR trig (3),
.BR math (7)
