.\" Process this file with
.\" groff -man -Tascii ttyname.3
.\"
.TH TTYNAME 3 "January 2026" "Substrate Standard C Library" "Library Calls Manual"
.SH NAME
ttyname \- return name of a terminal
.SH LIBRARY
Standard C library (libc, -lc)
.SH SYNOPSIS
.B #include <unistd.h>
.PP
.BI "char *ttyname(int " fd ");"
.SH DESCRIPTION
The function
.B ttyname
() returns a pointer to the null-terminated pathname of the terminal
device that is open on the file descriptor
.IR fd ,
or NULL on error (for example, if
.I fd
is not connected to a terminal).
.SH RETURN VALUE
The function
.B ttyname
() returns a pointer to a pathname on success. On error, NULL is returned.
.SH EXAMPLES
.B Program source
.nf

#include <unistd.h>
#include <stdio.h>

int main(void) {
    char *name;
    if ((name = ttyname(STDIN_FILENO)) != NULL) {
        printf("Standard input is connected to %s\\n", name);
    } else {
        printf("Standard input is not a terminal\\n");
    }
    return 0;
}
.fi

.SH SEE ALSO
.BR intro(2),
.BR errno(3)
