#ifndef _SUNOS_SYSCALLS_H
#define _SUNOS_SYSCALLS_H

#define SUNOS_SYS_indir       0
#define SUNOS_SYS_exit        1
#define SUNOS_SYS_fork        2
#define SUNOS_SYS_read        3
#define SUNOS_SYS_write       4
#define SUNOS_SYS_open        5
#define SUNOS_SYS_close       6
#define SUNOS_SYS_wait4       7
#define SUNOS_SYS_creat       8
#define SUNOS_SYS_link        9
#define SUNOS_SYS_unlink      10
#define SUNOS_SYS_execv       11
#define SUNOS_SYS_chdir       12
#define SUNOS_SYS_time        13
#define SUNOS_SYS_mknod       14
#define SUNOS_SYS_chmod       15
#define SUNOS_SYS_chown       16
#define SUNOS_SYS_break       17
#define SUNOS_SYS_stat        18
#define SUNOS_SYS_lseek       19
#define SUNOS_SYS_getpid      20
#define SUNOS_SYS_mount       21
#define SUNOS_SYS_unmount     22
#define SUNOS_SYS_setuid      23
#define SUNOS_SYS_getuid      24
#define SUNOS_SYS_stime       25
#define SUNOS_SYS_ptrace      26
#define SUNOS_SYS_alarm       27
#define SUNOS_SYS_fstat       28
#define SUNOS_SYS_pause       29
#define SUNOS_SYS_utime       30
#define SUNOS_SYS_stty        31
#define SUNOS_SYS_gtty        32
#define SUNOS_SYS_access      33
#define SUNOS_SYS_nice        34
#define SUNOS_SYS_ftime       35
#define SUNOS_SYS_sync        36
#define SUNOS_SYS_kill        37
#define SUNOS_SYS_mkdir       39
#define SUNOS_SYS_rmdir       40
#define SUNOS_SYS_dup         41
#define SUNOS_SYS_pipe        42
#define SUNOS_SYS_times       43
#define SUNOS_SYS_profil      44
#define SUNOS_SYS_brk         45
#define SUNOS_SYS_setgid      46
#define SUNOS_SYS_getgid      47
#define SUNOS_SYS_sigvec      48
#define SUNOS_SYS_acct        51
#define SUNOS_SYS_ioctl       54
#define SUNOS_SYS_symlink     57
#define SUNOS_SYS_readlink    58
#define SUNOS_SYS_execve      59
#define SUNOS_SYS_umask       60
#define SUNOS_SYS_chroot      61
#define SUNOS_SYS_vfork       66
#define SUNOS_SYS_mmap        71
#define SUNOS_SYS_munmap      73
#define SUNOS_SYS_mprotect    74
#define SUNOS_SYS_getpgrp     81
#define SUNOS_SYS_setpgid     82
#define SUNOS_SYS_dup2        90
#define SUNOS_SYS_sigreturn   103

#endif /* _SUNOS_SYSCALLS_H */
#define SUNOS_SYS_lstat       40
