/*
 * ksyms.c - Kernel Symbol Resolution
 *
 * Maps kernel addresses (EIP) to function names for debugging.
 * Parses embedded symbol table from kernel.map at build time.
 *
 * TASKS.md L564: Map EIP to kernel function names (parsing map/sym file).
 */

#include <stdint.h>
#include <stdio.h>
#include <kern/console.h>

/* Symbol table entry */
struct ksym {
    uint32_t addr;      /* Symbol address */
    char name[56];      /* Symbol name (truncated to 55 chars + null) */
};

/*
 * The symbol table is generated by the build system (parsing kernel.map)
 * and linked into the final binary.
 */
extern struct ksym ksym_table[];
extern int ksym_count;

/*
 * Weak definitions to satisfy the first pass of the linker.
 * These will be overridden by the generated ksyms_table.o in the second pass.
 */
__attribute__((weak)) struct ksym ksym_table[] = {
    { 0xFFFFFFFF, "" }
};
__attribute__((weak)) int ksym_count = 0;

/*
 * ksym_lookup - Find symbol containing address
 *
 * Returns pointer to symbol entry, or NULL if not found.
 * Uses binary search for efficiency.
 */
const struct ksym *ksym_lookup(uint32_t addr) {
    if (ksym_count == 0) return NULL;
    if (addr < ksym_table[0].addr || addr > ksym_table[ksym_count - 1].addr) {
        return NULL;
    }
    
    /* Binary search for largest address <= addr */
    int low = 0;
    int high = ksym_count - 1;
    const struct ksym *result = NULL;
    
    while (low <= high) {
        int mid = (low + high) / 2;
        
        if (ksym_table[mid].addr <= addr) {
            result = &ksym_table[mid];
            low = mid + 1;
        } else {
            high = mid - 1;
        }
    }
    
    return result;
}

/*
 * ksym_resolve - Resolve address to symbol name with offset
 *
 * Writes result to buf: "function_name+0x123" or "0xADDRESS" if unknown.
 * Returns length written.
 */
int ksym_resolve(uint32_t addr, char *buf, int buflen) {
    const struct ksym *sym = ksym_lookup(addr);
    if (!buf || buflen <= 0) {
        return 0;
    }
    
    if (sym && sym->name[0]) {
        uint32_t offset = addr - sym->addr;
        if (offset == 0) {
            return snprintf(buf, (size_t)buflen, "%s", sym->name);
        } else {
            return snprintf(buf, (size_t)buflen, "%s+0x%x", sym->name, offset);
        }
    } else {
        return snprintf(buf, (size_t)buflen, "0x%08x", addr);
    }
}

/*
 * ksym_print - Print address with symbol resolution
 */
void ksym_print(uint32_t addr) {
    char buf[80];
    ksym_resolve(addr, buf, sizeof(buf));
    kprint(buf);
}

/*
 * ksym_init - Initialize symbol table
 */
void ksym_init(void) {
    char buf[64];
    sprintf(buf, "KSYMS: Loaded %d symbols\n", ksym_count);
    kprint(buf);
}
