include ../../Makefile.inc

PROG = init

.PHONY: all clean install

all:
	@true

clean:
	@true

install:
	@echo "Installing $(PROG) script..."
	install -m 755 ../../etc/init.sh $(DESTDIR)/sbin/$(PROG)
