.Dd October 26, 2023
.Dt PAX 1
.Os Substrate
.Sh NAME
.Nm pax
.Nd read and write file archives and copy directory hierarchies
.Sh SYNOPSIS
.Nm
.Op Fl cdnv
.Op Fl f Ar archive
.Op Fl s Ar replstr
.Ar ...
.br
.Nm
.Fl r
.Op Fl cdiknuv
.Op Fl f Ar archive
.Op Fl o Ar options
.Op Fl p Ar string
.Op Fl s Ar replstr
.Op Ar pattern ...
.br
.Nm
.Fl w
.Op Fl dituvX
.Op Fl b Ar blocksize
.Op Fl a
.Op Fl f Ar archive
.Op Fl o Ar options
.Op Fl s Ar replstr
.Op Fl x Ar format
.Op Ar file ...
.br
.Nm
.Fl r
.Fl w
.Op Fl diklntuvX
.Op Fl p Ar string
.Op Fl s Ar replstr
.Op Ar file ...
.Ar directory
.Sh DESCRIPTION
.Nm
will read, write, and list the members of an archive file and will copy directory hierarchies.
.Pp
The modes of operation are:
.Bl -tag -width flag
.It list
(default) List the contents of an archive.
.It read
.Pq Fl r
Read an archive and extract the files.
.It write
.Pq Fl w
Write files to an archive.
.It copy
.Pq Fl rw
Copy files to a destination directory.
.El
.Sh OPTIONS
.Bl -tag -width flag
.It Fl r
Read an archive file.
.It Fl w
Write files to an archive file.
.It Fl f Ar archive
Specify the name of the archive file.
.It Fl s Ar replstr
Modify file or archive member names according to the substitution expression
.Ar replstr .
.It Fl v
Verbose operation.
.It Fl x Ar format
Specify the output archive format (ustar, cpio, pax).
.El
.Sh STANDARDS
The
.Nm
utility is expected to be compliant with the
.St -p1003.2
specification.
.Sh AUTHORS
Implemented for Substrate OS.
