/*
 * output.c - C Code Generation for the Yacc parser
 *
 * Emits y.tab.c (parser source) and, when -d is set, y.tab.h (header).
 * Conforms to IEEE Std 1003.1-2024 (POSIX) for the yacc utility, including:
 *   - LALR(1) ACTION/GOTO tables compressed via yysindex/yyrindex/yygindex.
 *   - All required runtime macros: yyerrok, yyclearin, YYACCEPT, YYABORT,
 *     YYERROR, YYRECOVERING, YYEOF, YYEMPTY, YYERRCODE, YYMAXDEPTH.
 *   - Error recovery: pops the parse stack until the 'error' token can shift.
 *   - #ifndef guards on yyerror()/yylex() prototypes (POSIX 6.1).
 *   - -l suppresses #line directives.
 *   - -t selects YYDEBUG=1, -d emits the header.
 *   - -p prefix renames external symbols via #define indirection.
 */

#include "defs.h"

extern action **parser;
extern short final_state;
extern int SRtotal, RRtotal;

static void output_prolog(void);
static void output_stored_text(void);
static void output_token_defines(FILE *f, int header);
static void output_stype(FILE *f);
static void output_table_data(void);
static void output_short_table(const char *name, const short *t, int n);
static void output_skeleton(void);
static void output_actions_block(void);
static void output_epilogue(void);
static void output_line_directive(FILE *f, int line, const char *file);
static int valid_c_ident(const char *s);

void output(void) {
    output_prolog();
    output_stored_text();
    output_token_defines(output_file, 0);
    output_stype(output_file);
    output_table_data();
    output_skeleton();
    output_epilogue();

    if (dflag && defines_file != NULL) {
        fprintf(defines_file, "/* Generated by yacc -- do not edit. */\n\n");
        fprintf(defines_file, "#ifndef _y_tab_h_INCLUDED\n");
        fprintf(defines_file, "#define _y_tab_h_INCLUDED\n\n");
        output_token_defines(defines_file, 1);
        output_stype(defines_file);
        fprintf(defines_file, "extern YYSTYPE %slval;\n", symbol_prefix);
        fprintf(defines_file, "extern int    %schar;\n",  symbol_prefix);
        fprintf(defines_file, "extern int    %snerrs;\n", symbol_prefix);
        fprintf(defines_file, "extern int    %serrflag;\n", symbol_prefix);
        fprintf(defines_file, "int %sparse(void);\n", symbol_prefix);
        fprintf(defines_file, "\n#endif /* _y_tab_h_INCLUDED */\n");
    }
}

static int valid_c_ident(const char *s) {
    if (s == NULL || *s == '\0') return 0;
    if (!isalpha((unsigned char)s[0]) && s[0] != '_') return 0;
    for (s++; *s; s++)
        if (!isalnum((unsigned char)*s) && *s != '_') return 0;
    return 1;
}

static int reserved_name(const char *s) {
    return (strcmp(s, "$accept") == 0 ||
            strcmp(s, "$end") == 0 ||
            strcmp(s, "error") == 0 ||
            s[0] == '$' || s[0] == '@');
}

static void output_prolog(void) {
    fprintf(output_file, "/* Generated by yacc -- do not edit. */\n\n");

    if (symbol_prefix && strcmp(symbol_prefix, "yy") != 0) {
        fprintf(output_file, "#define yyparse  %sparse\n", symbol_prefix);
        fprintf(output_file, "#define yylex    %slex\n",   symbol_prefix);
        fprintf(output_file, "#define yyerror  %serror\n", symbol_prefix);
        fprintf(output_file, "#define yychar   %schar\n",  symbol_prefix);
        fprintf(output_file, "#define yyval    %sval\n",   symbol_prefix);
        fprintf(output_file, "#define yylval   %slval\n",  symbol_prefix);
        fprintf(output_file, "#define yydebug  %sdebug\n", symbol_prefix);
        fprintf(output_file, "#define yynerrs  %snerrs\n", symbol_prefix);
        fprintf(output_file, "#define yyerrflag %serrflag\n", symbol_prefix);
        fprintf(output_file, "#define yyss     %sss\n",    symbol_prefix);
        fprintf(output_file, "#define yyssp    %sssp\n",   symbol_prefix);
        fprintf(output_file, "#define yyvs     %svs\n",    symbol_prefix);
        fprintf(output_file, "#define yyvsp    %svsp\n",   symbol_prefix);
        fprintf(output_file, "#define yystacksize %sstacksize\n", symbol_prefix);
        fprintf(output_file, "#define yylhs    %slhs\n",   symbol_prefix);
        fprintf(output_file, "#define yylen    %slen\n",   symbol_prefix);
        fprintf(output_file, "#define yydefred %sdefred\n", symbol_prefix);
        fprintf(output_file, "#define yydgoto  %sdgoto\n", symbol_prefix);
        fprintf(output_file, "#define yysindex %ssindex\n", symbol_prefix);
        fprintf(output_file, "#define yyrindex %srindex\n", symbol_prefix);
        fprintf(output_file, "#define yygindex %sgindex\n", symbol_prefix);
        fprintf(output_file, "#define yytable  %stable\n", symbol_prefix);
        fprintf(output_file, "#define yycheck  %scheck\n", symbol_prefix);
        fprintf(output_file, "\n");
    }

    fprintf(output_file, "#include <stdio.h>\n");
    fprintf(output_file, "#include <string.h>\n\n");

    fprintf(output_file, "#ifndef YYDEBUG\n");
    fprintf(output_file, "#define YYDEBUG %d\n", tflag ? 1 : 0);
    fprintf(output_file, "#endif\n\n");

    fprintf(output_file, "#ifndef YYMAXDEPTH\n");
    fprintf(output_file, "#define YYMAXDEPTH 500\n");
    fprintf(output_file, "#endif\n\n");

    fprintf(output_file, "#ifndef YYSTACKSIZE\n");
    fprintf(output_file, "#define YYSTACKSIZE YYMAXDEPTH\n");
    fprintf(output_file, "#endif\n\n");
}

static void output_stored_text(void) {
    int c;
    if (code_file == NULL) return;
    if (!lflag) output_line_directive(output_file, 1, infile_name);
    rewind(code_file);
    while ((c = getc(code_file)) != EOF)
        putc(c, output_file);
}

static void output_token_defines(FILE *f, int header) {
    bucket *bp;
    if (header) fprintf(f, "/* Token definitions */\n");

    for (bp = first_symbol; bp != NULL; bp = bp->next) {
        if (bp->class != CLASS_TERM) continue;
        if (reserved_name(bp->name)) continue;          /* skip $end/error */
        if (!valid_c_ident(bp->name)) continue;         /* skip char literals */
        fprintf(f, "#define %-20s %d\n", bp->name, bp->value);
    }
    fprintf(f, "#define YYERRCODE %d\n", error_symbol ? error_symbol->value : 256);
    fprintf(f, "\n");
}

static void output_stype(FILE *f) {
    int c;
    fprintf(f, "#ifndef YYSTYPE_DEFINED\n#define YYSTYPE_DEFINED\n");
    if (union_defined && union_file != NULL) {
        fprintf(f, "typedef union YYSTYPE {\n");
        rewind(union_file);
        while ((c = getc(union_file)) != EOF) putc(c, f);
        fprintf(f, "\n} YYSTYPE;\n");
    } else {
        fprintf(f, "typedef int YYSTYPE;\n");
    }
    fprintf(f, "#endif\n\n");
}

static void output_short_table(const char *name, const short *t, int n) {
    int i;
    fprintf(output_file, "static const short %s[] = {\n", name);
    for (i = 0; i < n; i++)
        fprintf(output_file, "  %d,\n", t[i]);
    fprintf(output_file, "};\n\n");
}

static void output_table_data(void) {
    int i;
    short *yylhs;
    short *yylen;

    yylhs = (short *)calloc((size_t)nrules, sizeof(short));
    yylen = (short *)calloc((size_t)nrules, sizeof(short));
    if (!yylhs || !yylen) no_space();

    for (i = 0; i < nrules; i++) {
        int len = 0;
        int j;
        yylhs[i] = (short)(plhs[i] - ntokens);
        for (j = rrhs[i]; ritem[j] >= 0; j++) len++;
        yylen[i] = (short)len;
    }

    fprintf(output_file, "#define YYFINAL  %d\n", final_state);
    fprintf(output_file, "#define YYNTOKENS %d\n", ntokens);
    fprintf(output_file, "#define YYNNTS    %d\n", nvars);
    fprintf(output_file, "#define YYNRULES  %d\n", nrules);
    fprintf(output_file, "#define YYNSTATES %d\n", nstates);
    fprintf(output_file, "#define YYTABLESIZE %d\n\n", yytable_size);

    output_short_table("yylhs",    yylhs,    nrules);
    output_short_table("yylen",    yylen,    nrules);
    output_short_table("yydefred", yydefred, nstates);
    output_short_table("yydgoto",  yydgoto,  nvars);
    output_short_table("yysindex", yysindex, nstates);
    output_short_table("yyrindex", yyrindex, nstates);
    output_short_table("yygindex", yygindex, nvars);
    output_short_table("yytable",  yytable,  yytable_size);
    output_short_table("yycheck",  yycheck,  yytable_size);

    free(yylhs);
    free(yylen);
}

static void output_actions_block(void) {
    int c;
    if (action_file == NULL) return;
    fprintf(output_file, "    switch (yyn) {\n");
    rewind(action_file);
    while ((c = getc(action_file)) != EOF) putc(c, output_file);
    fprintf(output_file, "    }\n");
}

static const char skeleton_part1[] =
"#define YYEMPTY    (-1)\n"
"#define YYEOF      0\n"
"#define yyerrok    (yyerrflag = 0)\n"
"#define yyclearin  (yychar = YYEMPTY)\n"
"#define YYRECOVERING() (yyerrflag != 0)\n"
"#define YYACCEPT   goto yyaccept\n"
"#define YYABORT    goto yyabort\n"
"#define YYERROR    goto yyerrlab\n"
"\n"
"#ifndef yylex\n"
"extern int yylex(void);\n"
"#endif\n"
"#ifndef yyerror\n"
"extern void yyerror(const char *);\n"
"#endif\n"
"\n"
"int      yychar;\n"
"int      yynerrs;\n"
"int      yyerrflag;\n"
"YYSTYPE  yylval;\n"
"YYSTYPE  yyval;\n"
"#if YYDEBUG\n"
"int      yydebug;\n"
"#endif\n"
"\n"
"int yyparse(void)\n"
"{\n"
"    int yym, yyn, yystate;\n"
"    short yyss[YYSTACKSIZE];\n"
"    YYSTYPE yyvs[YYSTACKSIZE];\n"
"    short *yyssp;\n"
"    YYSTYPE *yyvsp;\n"
"\n"
"    yystate   = 0;\n"
"    yyerrflag = 0;\n"
"    yychar    = YYEMPTY;\n"
"    yynerrs   = 0;\n"
"    yyssp     = yyss;\n"
"    yyvsp     = yyvs;\n"
"    *yyssp    = 0;\n"
"\n"
"yyloop:\n"
"    if ((yyn = yydefred[yystate]) != 0) goto yyreduce;\n"
"    if (yychar < 0) {\n"
"        if ((yychar = yylex()) < 0) yychar = YYEOF;\n"
"#if YYDEBUG\n"
"        if (yydebug) fprintf(stderr, \"yacc: read token %d\\n\", yychar);\n"
"#endif\n"
"    }\n"
"\n"
"    if ((yyn = yysindex[yystate]) != 0 &&\n"
"        (yyn += yychar) >= 0 && yyn <= YYTABLESIZE &&\n"
"        yycheck[yyn] == (short)yychar) {\n"
"#if YYDEBUG\n"
"        if (yydebug) fprintf(stderr,\n"
"            \"yacc: shift, state %d -> state %d\\n\", yystate, yytable[yyn]);\n"
"#endif\n"
"        if (yyssp >= yyss + YYSTACKSIZE - 1) goto yyoverflow;\n"
"        yystate = yytable[yyn];\n"
"        *++yyssp = (short)yystate;\n"
"        *++yyvsp = yylval;\n"
"        yychar = YYEMPTY;\n"
"        if (yyerrflag > 0) yyerrflag--;\n"
"        goto yyloop;\n"
"    }\n"
"\n"
"    if ((yyn = yyrindex[yystate]) != 0 &&\n"
"        (yyn += yychar) >= 0 && yyn <= YYTABLESIZE &&\n"
"        yycheck[yyn] == (short)yychar) {\n"
"        yyn = yytable[yyn];\n"
"        goto yyreduce;\n"
"    }\n"
"    goto yyerrlab;\n"
"\n"
"yyerrlab:\n"
"    if (yyerrflag == 0) {\n"
"        yyerror(\"syntax error\");\n"
"        ++yynerrs;\n"
"    }\n"
"    if (yyerrflag < 3) {\n"
"        yyerrflag = 3;\n"
"        for (;;) {\n"
"            if ((yyn = yysindex[*yyssp]) != 0 &&\n"
"                (yyn += YYERRCODE) >= 0 && yyn <= YYTABLESIZE &&\n"
"                yycheck[yyn] == (short)YYERRCODE) {\n"
"                if (yyssp >= yyss + YYSTACKSIZE - 1) goto yyoverflow;\n"
"                yystate = yytable[yyn];\n"
"                *++yyssp = (short)yystate;\n"
"                *++yyvsp = yylval;\n"
"                goto yyloop;\n"
"            }\n"
"            if (yyssp <= yyss) goto yyabort;\n"
"            --yyssp; --yyvsp;\n"
"        }\n"
"    }\n"
"    if (yychar == YYEOF) goto yyabort;\n"
"    yychar = YYEMPTY;\n"
"    goto yyloop;\n"
"\n"
"yyreduce:\n"
"    yym = yylen[yyn];\n"
"    if (yym) yyval = yyvsp[1 - yym]; else memset(&yyval, 0, sizeof yyval);\n";

static const char skeleton_part2[] =
"    yyssp -= yym;\n"
"    yystate = *yyssp;\n"
"    yyvsp -= yym;\n"
"    yym = yylhs[yyn];\n"
"    if (yystate == 0 && yym == 0) {\n"
"        yystate = YYFINAL;\n"
"        *++yyssp = (short)YYFINAL;\n"
"        *++yyvsp = yyval;\n"
"        if (yychar < 0) {\n"
"            if ((yychar = yylex()) < 0) yychar = YYEOF;\n"
"        }\n"
"        if (yychar == YYEOF) goto yyaccept;\n"
"        goto yyloop;\n"
"    }\n"
"    if ((yyn = yygindex[yym]) != 0 &&\n"
"        (yyn += yystate) >= 0 && yyn <= YYTABLESIZE &&\n"
"        yycheck[yyn] == (short)yystate)\n"
"        yystate = yytable[yyn];\n"
"    else\n"
"        yystate = yydgoto[yym];\n"
"    if (yyssp >= yyss + YYSTACKSIZE - 1) goto yyoverflow;\n"
"    *++yyssp = (short)yystate;\n"
"    *++yyvsp = yyval;\n"
"    goto yyloop;\n"
"\n"
"yyoverflow:\n"
"    yyerror(\"yacc stack overflow\");\n"
"yyabort:\n"
"    return 1;\n"
"yyaccept:\n"
"    return 0;\n"
"}\n";

static void output_skeleton(void) {
    fputs(skeleton_part1, output_file);
    output_actions_block();
    fputs(skeleton_part2, output_file);
}

static void output_epilogue(void) {
    int c;
    if (epilogue_file == NULL) return;
    if (!lflag) output_line_directive(output_file, lineno, infile_name);
    rewind(epilogue_file);
    while ((c = getc(epilogue_file)) != EOF) putc(c, output_file);
}

static void output_line_directive(FILE *f, int line, const char *file) {
    if (lflag) return;
    fprintf(f, "#line %d \"%s\"\n", line, file ? file : "<stdin>");
}
