#ifndef _SUBSTRATE_SYS_SIGNAL_H
#define _SUBSTRATE_SYS_SIGNAL_H

#include <stdint.h>

#define NSIG 32

/*
 * Real-time signals.  With a 32-bit sigset_t and NSIG=32 the signal
 * number space is 1..31; signals 29 and 30 are the only slots not
 * already assigned a standard signal, so the RT range is [29,30] (see
 * include/signal.h — kept in sync with the userland header).  This is a
 * hard ABI constraint: a Linux-style [34,63] range would require a
 * 64-bit sigset_t, i.e. a whole-userland ABI break (every binary's
 * sigset_t / sigaction sa_mask / sigprocmask argument changes size), so
 * it is deliberately out of scope.
 *
 * Within [SIGRTMIN,SIGRTMAX] signals genuinely QUEUE: each sigqueue(2)
 * or kill()/psignal() of an RT signal enqueues a distinct instance
 * (carrying its own si_value/si_code), delivered one per handler
 * invocation, lowest signo first and FIFO within a signo, bounded at
 * RTSIG_QUEUE_MAX (see struct rtsig_entry below and the per-process
 * rtsig_q[] in <sys/proc.h>).  Standard signals keep the sig_pending
 * bitmask (POSIX permits non-queueing there).
 */
#define SIGRTMIN 29
#define SIGRTMAX 30

/* True for a queueing real-time signal number. */
#define SIG_IS_RT(s) ((s) >= SIGRTMIN && (s) <= SIGRTMAX)

// Forward declaration
struct process;
struct thread;

#define SIGHUP     1
#define SIGINT     2
#define SIGQUIT    3
#define SIGILL     4
#define SIGTRAP    5
#define SIGABRT    6
#define SIGBUS     7
#define SIGFPE     8
#define SIGKILL    9
#define SIGUSR1    10
#define SIGSEGV    11
#define SIGUSR2    12
#define SIGPIPE    13
#define SIGALRM    14
#define SIGTERM    15
#define SIGURG     16
#define SIGCHLD    17
#define SIGCONT    18
#define SIGSTOP    19
#define SIGTSTP    20
#define SIGTTIN    21
#define SIGTTOU    22
#define SIGPOLL    23
#define SIGIO      SIGPOLL
/* Resource-limit signals.  Values match include/signal.h; the kernel header
 * skipped straight from SIGPOLL to SIGVTALRM while nothing raised them. */
#define SIGXCPU    24
#define SIGXFSZ    25
#define SIGVTALRM  26
#define SIGPROF    27
#define SIGWINCH   28
#define SIGSYS     31

typedef void (*sig_t)(int);

#define SIG_DFL ((sig_t)0)
#define SIG_IGN ((sig_t)1)
#define SIG_ERR ((sig_t)-1)

struct sigaction {
    sig_t     sa_handler;
    uint32_t  sa_mask;
    int       sa_flags;
};

/* POSIX sa_flags values — MUST match include/signal.h (the userland
 * ABI) bit-for-bit.  Userland and kernel share the same `int sa_flags`
 * across the sigaction() syscall boundary; any drift between the two
 * headers turns SA_ONSTACK/SA_RESTART/SA_NODEFER/SA_RESETHAND into
 * silent no-ops.  Caught by tests/lib/c/torture_sigalrm sc4. */
#define SA_NOCLDSTOP 0x00000001
#define SA_NOCLDWAIT 0x00000002
#define SA_SIGINFO   0x00000004
#define SA_ONSTACK   0x00000008
#define SA_RESTART   0x00000010
#define SA_NODEFER   0x00000020
#define SA_RESETHAND 0x00000040

#ifndef __sigval_t_defined
#define __sigval_t_defined 1
union sigval {
    int   sival_int;
    void *sival_ptr;
};
#endif

typedef struct {
    int      si_signo;    /* Signal number */
    int      si_errno;    /* An errno value */
    int      si_code;     /* Signal code */
    int      si_pid;      /* Sending process ID */
    unsigned int si_uid;  /* Real user ID of sending process */
    void    *si_addr;     /* Memory location which caused fault */
    int      si_status;   /* Exit value or signal */
    union sigval si_value; /* sigqueue(2) payload (SI_QUEUE) */
    // Padding to 128 bytes usually
    int      _pad[25];
} siginfo_t;

/*
 * POSIX real-time signal queue (per process — see rtsig_q[] in proc.h).
 *
 * RTSIG_QUEUE_MAX bounds the number of simultaneously-queued RT-signal
 * instances a process may hold; sigqueue(2) returns EAGAIN once it is
 * reached (>= _POSIX_SIGQUEUE_MAX = 32).  Each occupied slot is one
 * pending instance carrying its own si_value/si_code.  rt_signo == 0
 * marks a free slot; rt_seq is a per-process monotonic FIFO key so the
 * oldest instance of a given signo is delivered first.
 */
#define RTSIG_QUEUE_MAX 64

struct rtsig_entry {
    uint16_t     rt_signo;   /* 0 = free slot, else the signal number  */
    int16_t      rt_code;    /* si_code (SI_USER / SI_QUEUE)            */
    uint32_t     rt_seq;     /* FIFO ordering key (per-process)        */
    union sigval rt_value;   /* si_value payload delivered to handler  */
    int32_t      rt_pid;     /* sending process pid   (siginfo si_pid) */
    uint32_t     rt_uid;     /* sending process ruid  (siginfo si_uid) */
};

/*
 * Native Substrate siginfo si_code contract.
 *
 * The native ABI is BSD-shaped. Linux personality code translates the user-
 * visible signal frame ABI separately and must not assume the native signal
 * contract is Linux.
 */
#define SI_USER        0
#define SI_KERNEL      1
#define SI_QUEUE      (-1)   /* sent by sigqueue(2) */
#define SI_TIMER      (-2)   /* generated by timer expiration */
#define SI_MESGQ      (-3)   /* generated by message-queue arrival */

/* si_code values for SIGCHLD (child status change).  Must match the
 * user-visible values in <sys/wait.h> so an SA_SIGINFO handler sees the
 * right code. */
#define CLD_EXITED     1   /* child exited normally */
#define CLD_KILLED     2   /* child terminated by signal, no core */
#define CLD_DUMPED     3   /* child terminated by signal, core dumped */
#define CLD_TRAPPED    4   /* traced child trapped */
#define CLD_STOPPED    5   /* child stopped */
#define CLD_CONTINUED  6   /* stopped child continued */

#define ILL_ILLOPC     1
#define ILL_PRVOPC     5

#define FPE_INTDIV     1
#define FPE_INTOVF     2
#define FPE_FLTDIV     3
#define FPE_FLTOVF     4
#define FPE_FLTUND     5
#define FPE_FLTRES     6
#define FPE_FLTINV     7
#define FPE_FLTSUB     8

#define SEGV_MAPERR    1
#define SEGV_ACCERR    2

/* si_code values for SIGBUS — POSIX.1-2024. */
#define BUS_ADRALN     1   /* invalid address alignment */
#define BUS_ADRERR     2   /* non-existent physical address */
#define BUS_OBJERR     3   /* object-specific hardware error (substrate:
                              also used for "no free physical page at
                              fault time" — kernel resource shortage,
                              not a userland-pointer bug) */

#define TRAP_BRKPT     1
#define TRAP_TRACE     2

// Signal bits
#define sigmask(sig) (1U << ((sig) - 1))

/* Signal property flags for the kernel-internal sigprop[] table.
 * These are NOT sa_flags — they classify default disposition per
 * signal number, used only by signal-delivery code in sys/kern/.
 * Previously named SA_KILL / SA_CORE / etc., which collided with the
 * userland sa_flags namespace (SA_ONSTACK / SA_RESTART / SA_NODEFER /
 * SA_RESETHAND now share the same low bits to match the userland
 * ABI).  Renamed to PROP_* to make the distinction unambiguous. */
#define PROP_KILL     0x0001  /* Default action: terminate process */
#define PROP_CORE     0x0002  /* Default action: terminate + core dump */
#define PROP_STOP     0x0004  /* Default action: stop the process */
#define PROP_IGNORE   0x0008  /* Default action: ignore the signal */
#define PROP_CONT     0x0010  /* Continue if stopped */
#define PROP_TTYSTOP  0x0020  /* Stop from TTY (can be ignored by orphan) */
#define PROP_CANTMASK 0x0040  /* Signal cannot be masked (SIGKILL, SIGSTOP) */

/* Default signal properties array (defined in sigprop.c) */
extern const uint8_t sigprop[NSIG];

/* Signal syscalls - using void* to match syscall_impl.h and avoid circular deps */
int sys_sigaction(int sig, const void *act, void *oact);
int sys_sigprocmask(int how, const void *set, void *oset);
int sys_sigpending(void *set);
int sys_sigsuspend(const void *mask);
int sys_kill(int pid, int sig);
int signal_send_group(int pgrp, int sig);
int sys_sigwait(const uint32_t *set, int *sig);
int sys_sigtimedwait(const uint32_t *set, siginfo_t *info, const void *timeout);

#include <stddef.h> // for size_t

// Alternative signal stack structure
typedef struct stack {
    void     *ss_sp;       // Stack base or pointer
    int       ss_flags;    // Flags
    size_t    ss_size;     // Stack size
} stack_t;

#define SS_ONSTACK 1
#define SS_DISABLE 2
#define MINSIGSTKSZ 2048
#define SIGSTKSZ    8192

int sys_sigaltstack(const void *ss, void *oss);

/*
 * POSIX asynchronous-event notification (struct sigevent) — the kernel only
 * consumes this for mq_notify(2), so it needs the SIGEV_SIGNAL fields.  Layout
 * MUST match the userland <signal.h> copy: it crosses the syscall boundary.
 */
#ifndef __sigval_t_defined
#define __sigval_t_defined 1
union sigval {
    int   sival_int;
    void *sival_ptr;
};
#endif

#define SIGEV_SIGNAL  0    /* notify via signal */
#define SIGEV_NONE    1    /* no notification */
#define SIGEV_THREAD  2    /* notify by spawning a thread (userspace only) */

struct sigevent {
    int            sigev_notify;               /* SIGEV_* */
    int            sigev_signo;                /* signal number (SIGEV_SIGNAL) */
    union sigval   sigev_value;                /* value passed to handler/thread */
    void         (*sigev_notify_function)(union sigval); /* SIGEV_THREAD */
    void          *sigev_notify_attributes;    /* pthread_attr_t * (SIGEV_THREAD) */
};

void psignal(struct process *p, int sig);
/* Post SIGCHLD to `parent` carrying a child status-change siginfo: si_code is
 * one of CLD_* and si_pid/si_uid/si_status describe the child, so a parent's
 * SA_SIGINFO SIGCHLD handler sees the correct code (POSIX). */
void sigchld_notify(struct process *parent, int code, int cpid,
                    unsigned int cuid, int status);

/* POSIX interruption policy for a self-restarting interruptible sleep
 * (nanosleep/clock_nanosleep): call after an early wake with signals pending.
 * Returns nonzero iff the sleep must abort with EINTR (a caught or terminating
 * signal is pending); returns 0 when the caller should resume sleeping (any
 * pending job-control stop is honoured in place, ignored signals discarded). */
int signal_sleep_interrupted(void);
void signal_wake_thread(struct thread *t, int sig);
/* Queue one process-wide real-time-signal instance; no-op for standard signals.
 * Returns 0 or -EAGAIN if the RT queue is full.  (Retained for ksyms/ABI; the
 * thread-directed thr_kill/pthread_kill path now uses signal_post_thread, which
 * sets the pending bit on the TARGET thread only.) */
int signal_rt_post(struct process *p, int sig);
/* Post `sig` to a single thread (thread-directed: pthread_kill/thr_kill), then
 * wake it if it is interruptibly blocked.  Handles real-time signals correctly:
 * a bare pending bit with no queued instance is dropped by the delivery path,
 * so an RT signal is enqueued (one instance, pending bit on `t` alone) rather
 * than merely OR'd into t->sig_pending. */
void signal_post_thread(struct thread *t, int sig);
void pgsignal(int pgrp, int sig);
void trapsignal(struct process *p, int sig, int code);
void sigexit(struct process *p, int sig);
void sendsig(void *handler, int sig, uint32_t mask, uint32_t flags, void *regs);

#include <sys/copy.h>

#endif
