.\" cat(1) man page
.TH CAT 1 "February 2026" "Substrate" "User Commands"
.SH NAME
cat \- concatenate files and print on standard output
.SH SYNOPSIS
.B cat
.RI [ OPTION ]...
.RI [ FILE ]...
.SH DESCRIPTION
Concatenate FILE(s) to standard output.
.PP
With no FILE, or when FILE is \-, read standard input.
.SH OPTIONS
.TP
.BR \-A ", " \-\-show\-all
Equivalent to \fB\-vET\fR.
.TP
.BR \-b ", " \-\-number\-nonblank
Number non-blank output lines, overrides \fB\-n\fR.
.TP
.B \-e
Equivalent to \fB\-vE\fR.
.TP
.BR \-E ", " \-\-show\-ends
Display $ at end of each line.
.TP
.BR \-n ", " \-\-number
Number all output lines.
.TP
.BR \-s ", " \-\-squeeze\-blank
Suppress repeated empty output lines.
.TP
.B \-t
Equivalent to \fB\-vT\fR.
.TP
.BR \-T ", " \-\-show\-tabs
Display TAB characters as ^I.
.TP
.B \-u
(ignored) Write unbuffered. This option is accepted for POSIX
compatibility but has no effect as output is already unbuffered.
.TP
.BR \-v ", " \-\-show\-nonprinting
Use ^ and M- notation for non-printing characters,
except for linefeed and tab.
.TP
.B \-\-help
Display help message and exit.
.TP
.B \-\-version
Output version information and exit.
.SH "NON-PRINTING CHARACTER NOTATION"
When \fB\-v\fR is specified, non-printing characters are displayed as follows:
.TP
Control characters (0x00-0x1F)
Displayed as ^@ through ^_
.TP
DEL (0x7F)
Displayed as ^?
.TP
High-bit characters (0x80-0x9F)
Displayed as M-^@ through M-^_
.TP
High-bit characters (0xA0-0xFE)
Displayed as M-\  through M-~
.TP
0xFF
Displayed as M-^?
.SH "EXIT STATUS"
.TP
0
All files were processed successfully.
.TP
1
An error occurred reading or writing one or more files.
.SH EXAMPLES
.TP
cat file
Output contents of file to standard output.
.TP
cat file1 file2 > combined
Concatenate file1 and file2 into combined.
.TP
cat -n file
Number all output lines.
.TP
cat -b file
Number only non-blank lines.
.TP
cat -s file
Squeeze multiple blank lines into one.
.TP
cat -A file
Show all non-printing characters, tabs, and end-of-line markers.
.SH "SEE ALSO"
.BR tac (1),
.BR head (1),
.BR tail (1),
.BR more (1)
.SH STANDARDS
The
.B cat
utility is compliant with POSIX.1-2017.
.PP
The options \fB\-b\fR, \fB\-e\fR, \fB\-n\fR, \fB\-s\fR, \fB\-t\fR, \fB\-v\fR,
\fB\-A\fR, \fB\-E\fR, and \fB\-T\fR are extensions.
.SH HISTORY
The
.B cat
utility appeared in Version 1 AT&T UNIX.
