#ifndef _OPENBSD_SYSCALLS_H
#define _OPENBSD_SYSCALLS_H

#define OPENBSD_SYS_syscall        0
#define OPENBSD_SYS_exit           1
#define OPENBSD_SYS_fork           2
#define OPENBSD_SYS_read           3
#define OPENBSD_SYS_write          4
#define OPENBSD_SYS_open           5
#define OPENBSD_SYS_close          6
#define OPENBSD_SYS_wait4          7
#define OPENBSD_SYS_creat          8
#define OPENBSD_SYS_link           9
#define OPENBSD_SYS_unlink         10
#define OPENBSD_SYS_obs_execv      11
#define OPENBSD_SYS_chdir          12
#define OPENBSD_SYS_fchdir         13
#define OPENBSD_SYS_mknod          14
#define OPENBSD_SYS_chmod          15
#define OPENBSD_SYS_chown          16
#define OPENBSD_SYS_break          17
#define OPENBSD_SYS_getfsstat      18
#define OPENBSD_SYS_lseek          19
#define OPENBSD_SYS_getpid         20
#define OPENBSD_SYS_mount          21
#define OPENBSD_SYS_unmount        22
#define OPENBSD_SYS_setuid         23
#define OPENBSD_SYS_getuid         24
#define OPENBSD_SYS_geteuid        25
#define OPENBSD_SYS_ptrace         26
#define OPENBSD_SYS_recvmsg        27
#define OPENBSD_SYS_sendmsg        28
#define OPENBSD_SYS_recvfrom       29
#define OPENBSD_SYS_accept         30
#define OPENBSD_SYS_getpeername    31
#define OPENBSD_SYS_getsockname    32
#define OPENBSD_SYS_access         33
#define OPENBSD_SYS_chflags        34
#define OPENBSD_SYS_fchflags       35
#define OPENBSD_SYS_sync           36
#define OPENBSD_SYS_kill           37
#define OPENBSD_SYS_compat_stat    38
#define OPENBSD_SYS_getppid        39
#define OPENBSD_SYS_compat_lstat   40
#define OPENBSD_SYS_dup            41
#define OPENBSD_SYS_pipe           42
#define OPENBSD_SYS_getegid        43
#define OPENBSD_SYS_profil         44
#define OPENBSD_SYS_ktrace         45
#define OPENBSD_SYS_sigaction      46
#define OPENBSD_SYS_getgid         47
#define OPENBSD_SYS_sigprocmask    48
#define OPENBSD_SYS_getlogin       49
#define OPENBSD_SYS_setlogin       50
#define OPENBSD_SYS_acct           51
#define OPENBSD_SYS_sigpending     52
#define OPENBSD_SYS_sigaltstack    53
#define OPENBSD_SYS_ioctl          54
#define OPENBSD_SYS_reboot         55
#define OPENBSD_SYS_revoke         56
#define OPENBSD_SYS_symlink        57
#define OPENBSD_SYS_readlink       58
#define OPENBSD_SYS_execve         59
#define OPENBSD_SYS_umask          60
#define OPENBSD_SYS_chroot         61
#define OPENBSD_SYS_compat_fstat   62
#define OPENBSD_SYS_compat_getkern 63
#define OPENBSD_SYS_getpagesize    64
#define OPENBSD_SYS_msync          65
#define OPENBSD_SYS_vfork          66
#define OPENBSD_SYS_obs_vread      67
#define OPENBSD_SYS_obs_vwrite     68
#define OPENBSD_SYS_sbrk           69
#define OPENBSD_SYS_sstk           70
#define OPENBSD_SYS_mmap           71
#define OPENBSD_SYS_vadvise        72
#define OPENBSD_SYS_munmap         73
#define OPENBSD_SYS_mprotect       74
#define OPENBSD_SYS_madvise        75
#define OPENBSD_SYS_obs_vhangup    76
#define OPENBSD_SYS_obs_vlimit     77
#define OPENBSD_SYS_mincore        78
#define OPENBSD_SYS_getgroups      79
#define OPENBSD_SYS_setgroups      80
#define OPENBSD_SYS_getpgrp        81
#define OPENBSD_SYS_setpgid        82
#define OPENBSD_SYS_setitimer      83
#define OPENBSD_SYS_compat_wait    84
#define OPENBSD_SYS_swapon         85
#define OPENBSD_SYS_getitimer      86
#define OPENBSD_SYS_gethostname    87
#define OPENBSD_SYS_sethostname    88
#define OPENBSD_SYS_getdtablesize  89
#define OPENBSD_SYS_dup2           90
#define OPENBSD_SYS_fcntl          92
#define OPENBSD_SYS_select         93
#define OPENBSD_SYS_fsync          95
#define OPENBSD_SYS_setpriority    96
#define OPENBSD_SYS_socket         97
#define OPENBSD_SYS_connect        98
#define OPENBSD_SYS_compat_accept  99
#define OPENBSD_SYS_getpriority    100
#define OPENBSD_SYS_compat_send    101
#define OPENBSD_SYS_compat_recv    102
#define OPENBSD_SYS_compat_sigret  103
#define OPENBSD_SYS_bind           104
#define OPENBSD_SYS_setsockopt     105
#define OPENBSD_SYS_listen         106
#define OPENBSD_SYS_obs_vtimes     107
#define OPENBSD_SYS_compat_sigvec  108
#define OPENBSD_SYS_compat_sigblk  109
#define OPENBSD_SYS_compat_sigset  110
#define OPENBSD_SYS_sigsuspend     111
#define OPENBSD_SYS_compat_sigstk  112
#define OPENBSD_SYS_compat_recvmsg 113
#define OPENBSD_SYS_compat_sendmsg 114
#define OPENBSD_SYS_obs_vtrace     115
#define OPENBSD_SYS_gettimeofday   116
#define OPENBSD_SYS_getrusage      117
#define OPENBSD_SYS_getsockopt     118
#define OPENBSD_SYS_readv          120
#define OPENBSD_SYS_writev         121
#define OPENBSD_SYS_kill_modern    122
#define OPENBSD_SYS_fchown         123
#define OPENBSD_SYS_fchmod         124
#define OPENBSD_SYS_setreuid       126
#define OPENBSD_SYS_setregid       127
#define OPENBSD_SYS_rename         128
#define OPENBSD_SYS_flock          131
#define OPENBSD_SYS_mkfifo         132
#define OPENBSD_SYS_sendto         133
#define OPENBSD_SYS_shutdown       134
#define OPENBSD_SYS_socketpair     135
#define OPENBSD_SYS_mkdir          136
#define OPENBSD_SYS_rmdir          137
#define OPENBSD_SYS_adjtime        140
#define OPENBSD_SYS_setsid         147
#define OPENBSD_SYS_quotactl       148
#define OPENBSD_SYS_nfssvc         155
#define OPENBSD_SYS_getfh          161
#define OPENBSD_SYS___tmpfd        164
#define OPENBSD_SYS_sysarch        165
#define OPENBSD_SYS_lseek_modern   166
#define OPENBSD_SYS_truncate       167
#define OPENBSD_SYS_ftruncate      168
#define OPENBSD_SYS_pread          169
#define OPENBSD_SYS_pwrite         170
#define OPENBSD_SYS_preadv         171
#define OPENBSD_SYS_pwritev        172
#define OPENBSD_SYS_setgid         181
#define OPENBSD_SYS_setegid        182
#define OPENBSD_SYS_seteuid        183
#define OPENBSD_SYS_pathconfat     190
#define OPENBSD_SYS_pathconf       191
#define OPENBSD_SYS_fpathconf      192
#define OPENBSD_SYS_swapctl        193
#define OPENBSD_SYS_getrlimit      194
#define OPENBSD_SYS_setrlimit      195
#define OPENBSD_SYS_sysctl         202
#define OPENBSD_SYS_mlock          203
#define OPENBSD_SYS_munlock        204
#define OPENBSD_SYS_getpgid        207
#define OPENBSD_SYS_utrace         209
#define OPENBSD_SYS_semget         221
#define OPENBSD_SYS_msgget         225
#define OPENBSD_SYS_msgsnd         226
#define OPENBSD_SYS_msgrcv         227
#define OPENBSD_SYS_shmat          228
#define OPENBSD_SYS_shmdt          230
#define OPENBSD_SYS_minherit       250
#define OPENBSD_SYS_poll           252
#define OPENBSD_SYS_issetugid      253
#define OPENBSD_SYS_lchown         254
#define OPENBSD_SYS_getsid         255
#define OPENBSD_SYS_msync_modern   256
#define OPENBSD_SYS_pipe_modern    263
#define OPENBSD_SYS_fhopen         264
#define OPENBSD_SYS_kqueue         269
#define OPENBSD_SYS_mlockall       271
#define OPENBSD_SYS_munlockall     272
#define OPENBSD_SYS_getresuid      281
#define OPENBSD_SYS_setresuid      282
#define OPENBSD_SYS_getresgid      283
#define OPENBSD_SYS_setresgid      284
#define OPENBSD_SYS_closefrom      287
#define OPENBSD_SYS_sigaltstack_modern 288
#define OPENBSD_SYS_shmget         289
#define OPENBSD_SYS_semop          290
#define OPENBSD_SYS_fhstat         294
#define OPENBSD_SYS___semctl       295
#define OPENBSD_SYS_shmctl         296
#define OPENBSD_SYS_msgctl         297
#define OPENBSD_SYS_sched_yield    298
#define OPENBSD_SYS_getthrid       299
#define OPENBSD_SYS___thrwakeup    301
#define OPENBSD_SYS___threxit      302
#define OPENBSD_SYS___thrsigdivert 303
#define OPENBSD_SYS___getcwd       304
#define OPENBSD_SYS_adjfreq        305
#define OPENBSD_SYS_setrtable      310
#define OPENBSD_SYS_getrtable      311
#define OPENBSD_SYS_faccessat      313
#define OPENBSD_SYS_fchmodat       314
#define OPENBSD_SYS_fchownat       315
#define OPENBSD_SYS_linkat         317
#define OPENBSD_SYS_mkdirat        318
#define OPENBSD_SYS_mkfifoat       319
#define OPENBSD_SYS_mknodat        320
#define OPENBSD_SYS_openat         321
#define OPENBSD_SYS_readlinkat     322
#define OPENBSD_SYS_renameat       323
#define OPENBSD_SYS_symlinkat      324
#define OPENBSD_SYS_unlinkat       325
#define OPENBSD_SYS___set_tcb      329
#define OPENBSD_SYS___get_tcb      330

#endif /* _OPENBSD_SYSCALLS_H */
