.\"
.\" STAT(2) - Substrate Native Personality
.\"
.TH STAT 2 "January 2026" "Substrate OS" "System Calls"
.SH NAME
stat, lstat, fstat \- get file status
.SH SYNOPSIS
.nf
.B #include <sys/stat.h>
.PP
.BI "int stat(const char *" pathname ", struct stat *" statbuf ");
.BI "int lstat(const char *" pathname ", struct stat *" statbuf ");
.BI "int fstat(int " fd ", struct stat *" statbuf ");
.fi
.SH DESCRIPTION
These functions return information about a file in the buffer pointed
to by
.IR statbuf .
.PP
.BR stat ()
retrieves information about the file pointed to by
.IR pathname .
.PP
.BR lstat ()
is identical to
.BR stat (),
except that if
.I pathname
is a symbolic link, it returns information about the link itself,
not the file it refers to.
.PP
.BR fstat ()
retrieves information about the file referred to by the file
descriptor
.IR fd .
.SS The stat structure
.nf
struct stat {
    uint32_t  st_dev;      /* ID of device containing file */
    uint32_t  st_ino;      /* Inode number */
    uint16_t  st_mode;     /* File type and mode */
    uint16_t  st_nlink;    /* Number of hard links */
    uint16_t  st_uid;      /* User ID of owner */
    uint16_t  st_gid;      /* Group ID of owner */
    uint32_t  st_rdev;     /* Device ID (if special file) */
    int64_t   st_size;     /* Total size, in bytes */
    uint32_t  st_blksize;  /* Block size for filesystem I/O */
    int64_t   st_blocks;   /* Number of 512B blocks allocated */
    int64_t   st_atime;    /* Time of last access */
    int64_t   st_mtime;    /* Time of last modification */
    int64_t   st_ctime;    /* Time of last status change */
};
.fi
.SH RETURN VALUE
On success, zero is returned.
.PP
On error, \-1 is returned, and
.I errno
is set appropriately.
.SH ERRORS
.TP
.B ENOENT
A component of
.I pathname
does not exist.
.TP
.B EBADF
.I fd
is not a valid open file descriptor.
.SH NOTES
.SS Substrate Native ABI
.nf
stat:   Syscall Number: 106
lstat:  Syscall Number: 107 (SYS_LSTAT)
fstat:  Syscall Number: 108 (SYS_FSTAT)
.fi
.SS 64-bit Time
Substrate uses 64-bit
.B time_t
for all timestamp fields, avoiding Y2038 issues.
.SH SEE ALSO
.BR access (2),
.BR open (2),
.BR substrate (7)
.SH STANDARDS
POSIX.1-2001, POSIX.1-2008.
