.\" Copyright (c) 2026 Kirn Gill II <segin2005@gmail.com>
.\" All rights reserved.
.\"
.Dd January 25, 2026
.Dt RESOURCE 9
.Os Substrate
.Sh NAME
.Nm struct resource
.Nd hardware resource management structure
.Sh SYNOPSIS
.In kern/resource.h
.Sh DESCRIPTION
The
.Vt struct resource
structure represents a range of hardware resources, such as I/O ports, memory addresses, interrupt vectors, or DMA channels. It supports hierarchical organization (tree structure) for resource allocation and conflict tracking.
.Sh TYPES
.Bl -tag -width "RES_DMA"
.It Dv RES_IO
I/O Port range.
.It Dv RES_MEM
Memory-Mapped I/O range.
.It Dv RES_IRQ
Interrupt Request line(s).
.It Dv RES_DMA
DMA Channel(s).
.El
.Sh FIELDS
.Bl -tag -width "sibling"
.It Vt uint32_t type
Resource type identifier.
.It Vt resource_size_t start
Start address or index of the resource range (inclusive).
.It Vt resource_size_t end
End address or index of the resource range (inclusive).
.It Vt uint32_t flags
Resource attribute flags (e.g., shared, reserved).
.It Vt struct resource *parent
Pointer to the parent resource container.
.It Vt struct resource *sibling
Pointer to the next resource in the same container.
.It Vt struct resource *child
Pointer to the first child resource allocated from this range.
.It Vt struct device *owner
Pointer to the device that owns/requested this resource.
.El
.Sh FUNCTIONS
.Bl -tag -width "resource_overlaps"
.It Fn bool resource_contains "struct resource *r1" "struct resource *r2"
Returns true if range r1 fully contains range r2.
.It Fn bool resource_overlaps "struct resource *r1" "struct resource *r2"
Returns true if range r1 overlaps with range r2.
.It Fn resource_size_t resource_size "struct resource *r"
Returns the size of the resource range.
.El
.Sh SEE ALSO
.Xr device 9
.Sh HISTORY
The
.Vt struct resource
interface first appeared in Substrate.
.Sh AUTHORS
.An Kirn Gill II Aq Mt segin2005@gmail.com
